/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceEventParamError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceEventParamError{}

// GetByContractResponseHitsHitsSourceEventParamError Details of the error response returned for a given activity.
type GetByContractResponseHitsHitsSourceEventParamError struct {
	// HTTP status code for the given activity.
	HttpStatus *int32 `json:"httpStatus,omitempty"`
	// An array of error messages corresponding to the given activity.
	Messages []GetByContractResponseHitsHitsSourceEventParamErrorMessages `json:"messages,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceEventParamError instantiates a new GetByContractResponseHitsHitsSourceEventParamError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceEventParamError() *GetByContractResponseHitsHitsSourceEventParamError {
	this := GetByContractResponseHitsHitsSourceEventParamError{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceEventParamErrorWithDefaults instantiates a new GetByContractResponseHitsHitsSourceEventParamError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceEventParamErrorWithDefaults() *GetByContractResponseHitsHitsSourceEventParamError {
	this := GetByContractResponseHitsHitsSourceEventParamError{}
	return &this
}

// GetHttpStatus returns the HttpStatus field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParamError) GetHttpStatus() int32 {
	if o == nil || IsNil(o.HttpStatus) {
		var ret int32
		return ret
	}
	return *o.HttpStatus
}

// GetHttpStatusOk returns a tuple with the HttpStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamError) GetHttpStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpStatus) {
		return nil, false
	}
	return o.HttpStatus, true
}

// HasHttpStatus returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamError) HasHttpStatus() bool {
	if o != nil && !IsNil(o.HttpStatus) {
		return true
	}

	return false
}

// SetHttpStatus gets a reference to the given int32 and assigns it to the HttpStatus field.
func (o *GetByContractResponseHitsHitsSourceEventParamError) SetHttpStatus(v int32) {
	o.HttpStatus = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParamError) GetMessages() []GetByContractResponseHitsHitsSourceEventParamErrorMessages {
	if o == nil || IsNil(o.Messages) {
		var ret []GetByContractResponseHitsHitsSourceEventParamErrorMessages
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamError) GetMessagesOk() ([]GetByContractResponseHitsHitsSourceEventParamErrorMessages, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamError) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []GetByContractResponseHitsHitsSourceEventParamErrorMessages and assigns it to the Messages field.
func (o *GetByContractResponseHitsHitsSourceEventParamError) SetMessages(v []GetByContractResponseHitsHitsSourceEventParamErrorMessages) {
	o.Messages = v
}

func (o GetByContractResponseHitsHitsSourceEventParamError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceEventParamError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HttpStatus) {
		toSerialize["httpStatus"] = o.HttpStatus
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceEventParamError struct {
	value *GetByContractResponseHitsHitsSourceEventParamError
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamError) Get() *GetByContractResponseHitsHitsSourceEventParamError {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamError) Set(val *GetByContractResponseHitsHitsSourceEventParamError) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamError) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceEventParamError(val *GetByContractResponseHitsHitsSourceEventParamError) *NullableGetByContractResponseHitsHitsSourceEventParamError {
	return &NullableGetByContractResponseHitsHitsSourceEventParamError{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
