/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceMeta{}

// GetByContractResponseHitsHitsSourceMeta Meta information about the activity event.
type GetByContractResponseHitsHitsSourceMeta struct {
	// The values returned is currently 0.1.
	AuditVersion *float32 `json:"auditVersion,omitempty"`
	// Identifier of the individual request which triggered the activity.
	RequestId *string `json:"requestId,omitempty"`
	// Identifier of the provisioning queue reference. Use this value to group different events that were part of the same provisioning request.
	QueueRefId *int32 `json:"queueRefId,omitempty"`
	// Combined date and time of the activity event in UTC.
	Time *string `json:"time,omitempty"`
	// Identifier of the transaction which triggered the activity.
	TransactionId *string `json:"transactionId,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceMeta instantiates a new GetByContractResponseHitsHitsSourceMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceMeta() *GetByContractResponseHitsHitsSourceMeta {
	this := GetByContractResponseHitsHitsSourceMeta{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceMetaWithDefaults instantiates a new GetByContractResponseHitsHitsSourceMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceMetaWithDefaults() *GetByContractResponseHitsHitsSourceMeta {
	this := GetByContractResponseHitsHitsSourceMeta{}
	return &this
}

// GetAuditVersion returns the AuditVersion field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceMeta) GetAuditVersion() float32 {
	if o == nil || IsNil(o.AuditVersion) {
		var ret float32
		return ret
	}
	return *o.AuditVersion
}

// GetAuditVersionOk returns a tuple with the AuditVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) GetAuditVersionOk() (*float32, bool) {
	if o == nil || IsNil(o.AuditVersion) {
		return nil, false
	}
	return o.AuditVersion, true
}

// HasAuditVersion returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) HasAuditVersion() bool {
	if o != nil && !IsNil(o.AuditVersion) {
		return true
	}

	return false
}

// SetAuditVersion gets a reference to the given float32 and assigns it to the AuditVersion field.
func (o *GetByContractResponseHitsHitsSourceMeta) SetAuditVersion(v float32) {
	o.AuditVersion = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceMeta) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetByContractResponseHitsHitsSourceMeta) SetRequestId(v string) {
	o.RequestId = &v
}

// GetQueueRefId returns the QueueRefId field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceMeta) GetQueueRefId() int32 {
	if o == nil || IsNil(o.QueueRefId) {
		var ret int32
		return ret
	}
	return *o.QueueRefId
}

// GetQueueRefIdOk returns a tuple with the QueueRefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) GetQueueRefIdOk() (*int32, bool) {
	if o == nil || IsNil(o.QueueRefId) {
		return nil, false
	}
	return o.QueueRefId, true
}

// HasQueueRefId returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) HasQueueRefId() bool {
	if o != nil && !IsNil(o.QueueRefId) {
		return true
	}

	return false
}

// SetQueueRefId gets a reference to the given int32 and assigns it to the QueueRefId field.
func (o *GetByContractResponseHitsHitsSourceMeta) SetQueueRefId(v int32) {
	o.QueueRefId = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceMeta) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *GetByContractResponseHitsHitsSourceMeta) SetTime(v string) {
	o.Time = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceMeta) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceMeta) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *GetByContractResponseHitsHitsSourceMeta) SetTransactionId(v string) {
	o.TransactionId = &v
}

func (o GetByContractResponseHitsHitsSourceMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuditVersion) {
		toSerialize["auditVersion"] = o.AuditVersion
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.QueueRefId) {
		toSerialize["queueRefId"] = o.QueueRefId
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceMeta struct {
	value *GetByContractResponseHitsHitsSourceMeta
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceMeta) Get() *GetByContractResponseHitsHitsSourceMeta {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceMeta) Set(val *GetByContractResponseHitsHitsSourceMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceMeta(val *GetByContractResponseHitsHitsSourceMeta) *NullableGetByContractResponseHitsHitsSourceMeta {
	return &NullableGetByContractResponseHitsHitsSourceMeta{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
