/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the ReferenceById type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceById{}

// ReferenceById Describes a reference to a specific activity log source.
type ReferenceById struct {
	// The Contract ID
	Id *int64 `json:"id,omitempty"`
	// A string indicating the type
	Type *string `json:"type,omitempty"`
	// A URL reference
	Href *string `json:"href,omitempty"`
}

// NewReferenceById instantiates a new ReferenceById object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceById() *ReferenceById {
	this := ReferenceById{}

	return &this
}

// NewReferenceByIdWithDefaults instantiates a new ReferenceById object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceByIdWithDefaults() *ReferenceById {
	this := ReferenceById{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReferenceById) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceById) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReferenceById) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ReferenceById) SetId(v int64) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReferenceById) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceById) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReferenceById) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReferenceById) SetType(v string) {
	o.Type = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ReferenceById) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceById) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ReferenceById) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ReferenceById) SetHref(v string) {
	o.Href = &v
}

func (o ReferenceById) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceById) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	return toSerialize, nil
}

type NullableReferenceById struct {
	value *ReferenceById
	isSet bool
}

func (v NullableReferenceById) Get() *ReferenceById {
	return v.value
}

func (v *NullableReferenceById) Set(val *ReferenceById) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceById) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceById) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceById(val *ReferenceById) *NullableReferenceById {
	return &NullableReferenceById{value: val, isSet: true}
}

func (v NullableReferenceById) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceById) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
