/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceEventResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceEventResources{}

// GetByContractResponseHitsHitsSourceEventResources struct for GetByContractResponseHitsHitsSourceEventResources
type GetByContractResponseHitsHitsSourceEventResources struct {
	// An array of items containing a string describing the action that was performed on the resource. There are a large number of possible values returned here.  Some example values are  * in the security domain `sec.user.create` for a user    creation,  * in the IP domain `ip.ipblock.reserve` for reserving an    IP block, * in the virtual resources domain `vr.firewall.activate` for    a firewall activation or * in the snapshot domain `sn.snapshot.create` for creating   a snapshot.
	Action []string `json:"action,omitempty"`
	// Identifier of the given resource.
	Id *string `json:"id,omitempty"`
	// Type of the given resource. Example values are  * `datacenter`, * `firewallrule` or * `backupUnit`.
	Type *string `json:"type,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceEventResources instantiates a new GetByContractResponseHitsHitsSourceEventResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceEventResources() *GetByContractResponseHitsHitsSourceEventResources {
	this := GetByContractResponseHitsHitsSourceEventResources{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceEventResourcesWithDefaults instantiates a new GetByContractResponseHitsHitsSourceEventResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceEventResourcesWithDefaults() *GetByContractResponseHitsHitsSourceEventResources {
	this := GetByContractResponseHitsHitsSourceEventResources{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetAction() []string {
	if o == nil || IsNil(o.Action) {
		var ret []string
		return ret
	}
	return o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetActionOk() ([]string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given []string and assigns it to the Action field.
func (o *GetByContractResponseHitsHitsSourceEventResources) SetAction(v []string) {
	o.Action = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetByContractResponseHitsHitsSourceEventResources) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventResources) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetByContractResponseHitsHitsSourceEventResources) SetType(v string) {
	o.Type = &v
}

func (o GetByContractResponseHitsHitsSourceEventResources) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceEventResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceEventResources struct {
	value *GetByContractResponseHitsHitsSourceEventResources
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceEventResources) Get() *GetByContractResponseHitsHitsSourceEventResources {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceEventResources) Set(val *GetByContractResponseHitsHitsSourceEventResources) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceEventResources) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceEventResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceEventResources(val *GetByContractResponseHitsHitsSourceEventResources) *NullableGetByContractResponseHitsHitsSourceEventResources {
	return &NullableGetByContractResponseHitsHitsSourceEventResources{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceEventResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceEventResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
