/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponse{}

// GetByContractResponse Activity log data related to the specific contractId
type GetByContractResponse struct {
	Hits *GetByContractResponseHits `json:"hits,omitempty"`
}

// NewGetByContractResponse instantiates a new GetByContractResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponse() *GetByContractResponse {
	this := GetByContractResponse{}

	return &this
}

// NewGetByContractResponseWithDefaults instantiates a new GetByContractResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseWithDefaults() *GetByContractResponse {
	this := GetByContractResponse{}
	return &this
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetByContractResponse) GetHits() GetByContractResponseHits {
	if o == nil || IsNil(o.Hits) {
		var ret GetByContractResponseHits
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponse) GetHitsOk() (*GetByContractResponseHits, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetByContractResponse) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given GetByContractResponseHits and assigns it to the Hits field.
func (o *GetByContractResponse) SetHits(v GetByContractResponseHits) {
	o.Hits = &v
}

func (o GetByContractResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	return toSerialize, nil
}

type NullableGetByContractResponse struct {
	value *GetByContractResponse
	isSet bool
}

func (v NullableGetByContractResponse) Get() *GetByContractResponse {
	return v.value
}

func (v *NullableGetByContractResponse) Set(val *GetByContractResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponse(val *GetByContractResponse) *NullableGetByContractResponse {
	return &NullableGetByContractResponse{value: val, isSet: true}
}

func (v NullableGetByContractResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
