/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSource{}

// GetByContractResponseHitsHitsSource The payload of a single activity event.
type GetByContractResponseHitsHitsSource struct {
	Principal *GetByContractResponseHitsHitsSourcePrincipal `json:"principal,omitempty"`
	Meta      *GetByContractResponseHitsHitsSourceMeta      `json:"meta,omitempty"`
	Event     *GetByContractResponseHitsHitsSourceEvent     `json:"event,omitempty"`
}

// NewGetByContractResponseHitsHitsSource instantiates a new GetByContractResponseHitsHitsSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSource() *GetByContractResponseHitsHitsSource {
	this := GetByContractResponseHitsHitsSource{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceWithDefaults instantiates a new GetByContractResponseHitsHitsSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceWithDefaults() *GetByContractResponseHitsHitsSource {
	this := GetByContractResponseHitsHitsSource{}
	return &this
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSource) GetPrincipal() GetByContractResponseHitsHitsSourcePrincipal {
	if o == nil || IsNil(o.Principal) {
		var ret GetByContractResponseHitsHitsSourcePrincipal
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSource) GetPrincipalOk() (*GetByContractResponseHitsHitsSourcePrincipal, bool) {
	if o == nil || IsNil(o.Principal) {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSource) HasPrincipal() bool {
	if o != nil && !IsNil(o.Principal) {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given GetByContractResponseHitsHitsSourcePrincipal and assigns it to the Principal field.
func (o *GetByContractResponseHitsHitsSource) SetPrincipal(v GetByContractResponseHitsHitsSourcePrincipal) {
	o.Principal = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSource) GetMeta() GetByContractResponseHitsHitsSourceMeta {
	if o == nil || IsNil(o.Meta) {
		var ret GetByContractResponseHitsHitsSourceMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSource) GetMetaOk() (*GetByContractResponseHitsHitsSourceMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSource) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given GetByContractResponseHitsHitsSourceMeta and assigns it to the Meta field.
func (o *GetByContractResponseHitsHitsSource) SetMeta(v GetByContractResponseHitsHitsSourceMeta) {
	o.Meta = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSource) GetEvent() GetByContractResponseHitsHitsSourceEvent {
	if o == nil || IsNil(o.Event) {
		var ret GetByContractResponseHitsHitsSourceEvent
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSource) GetEventOk() (*GetByContractResponseHitsHitsSourceEvent, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSource) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given GetByContractResponseHitsHitsSourceEvent and assigns it to the Event field.
func (o *GetByContractResponseHitsHitsSource) SetEvent(v GetByContractResponseHitsHitsSourceEvent) {
	o.Event = &v
}

func (o GetByContractResponseHitsHitsSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Principal) {
		toSerialize["principal"] = o.Principal
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSource struct {
	value *GetByContractResponseHitsHitsSource
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSource) Get() *GetByContractResponseHitsHitsSource {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSource) Set(val *GetByContractResponseHitsHitsSource) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSource) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSource(val *GetByContractResponseHitsHitsSource) *NullableGetByContractResponseHitsHitsSource {
	return &NullableGetByContractResponseHitsHitsSource{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
