/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHits{}

// GetByContractResponseHits The container for the found activity event data.
type GetByContractResponseHits struct {
	// A count of total number of available activity events.
	Total *int32                          `json:"total,omitempty"`
	Hits  []GetByContractResponseHitsHits `json:"hits,omitempty"`
}

// NewGetByContractResponseHits instantiates a new GetByContractResponseHits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHits() *GetByContractResponseHits {
	this := GetByContractResponseHits{}

	return &this
}

// NewGetByContractResponseHitsWithDefaults instantiates a new GetByContractResponseHits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsWithDefaults() *GetByContractResponseHits {
	this := GetByContractResponseHits{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetByContractResponseHits) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHits) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetByContractResponseHits) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetByContractResponseHits) SetTotal(v int32) {
	o.Total = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetByContractResponseHits) GetHits() []GetByContractResponseHitsHits {
	if o == nil || IsNil(o.Hits) {
		var ret []GetByContractResponseHitsHits
		return ret
	}
	return o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHits) GetHitsOk() ([]GetByContractResponseHitsHits, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetByContractResponseHits) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given []GetByContractResponseHitsHits and assigns it to the Hits field.
func (o *GetByContractResponseHits) SetHits(v []GetByContractResponseHitsHits) {
	o.Hits = v
}

func (o GetByContractResponseHits) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHits struct {
	value *GetByContractResponseHits
	isSet bool
}

func (v NullableGetByContractResponseHits) Get() *GetByContractResponseHits {
	return v.value
}

func (v *NullableGetByContractResponseHits) Set(val *GetByContractResponseHits) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHits) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHits(val *GetByContractResponseHits) *NullableGetByContractResponseHits {
	return &NullableGetByContractResponseHits{value: val, isSet: true}
}

func (v NullableGetByContractResponseHits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
