/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceEvent{}

// GetByContractResponseHitsHitsSourceEvent Details specific to the activity event.
type GetByContractResponseHitsHitsSourceEvent struct {
	Param *GetByContractResponseHitsHitsSourceEventParam `json:"param,omitempty"`
	// An array of resources affected by the given activity.
	Resources []GetByContractResponseHitsHitsSourceEventResources `json:"resources,omitempty"`
	// Message explaining the current status of the request.
	Message *string `json:"message,omitempty"`
	// The current status of the request.
	Status *string `json:"status,omitempty"`
	// Type of the activity event. The exact contents of the `event` object will vary depending on this value.  There are a large number of possible values, examples are * `Error` for a request that couldn't be completed, * `RequestAccepted` for an incoming request (e.g. via HTTP), * `RequestStatusUpdate` for a later update about a request which was   logged earlier, * `Provision` for resource provisionings running in the background or  * `DCDUserEvent` for events about a DCD user.
	Type *string `json:"type,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceEvent instantiates a new GetByContractResponseHitsHitsSourceEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceEvent() *GetByContractResponseHitsHitsSourceEvent {
	this := GetByContractResponseHitsHitsSourceEvent{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceEventWithDefaults instantiates a new GetByContractResponseHitsHitsSourceEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceEventWithDefaults() *GetByContractResponseHitsHitsSourceEvent {
	this := GetByContractResponseHitsHitsSourceEvent{}
	return &this
}

// GetParam returns the Param field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEvent) GetParam() GetByContractResponseHitsHitsSourceEventParam {
	if o == nil || IsNil(o.Param) {
		var ret GetByContractResponseHitsHitsSourceEventParam
		return ret
	}
	return *o.Param
}

// GetParamOk returns a tuple with the Param field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) GetParamOk() (*GetByContractResponseHitsHitsSourceEventParam, bool) {
	if o == nil || IsNil(o.Param) {
		return nil, false
	}
	return o.Param, true
}

// HasParam returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) HasParam() bool {
	if o != nil && !IsNil(o.Param) {
		return true
	}

	return false
}

// SetParam gets a reference to the given GetByContractResponseHitsHitsSourceEventParam and assigns it to the Param field.
func (o *GetByContractResponseHitsHitsSourceEvent) SetParam(v GetByContractResponseHitsHitsSourceEventParam) {
	o.Param = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEvent) GetResources() []GetByContractResponseHitsHitsSourceEventResources {
	if o == nil || IsNil(o.Resources) {
		var ret []GetByContractResponseHitsHitsSourceEventResources
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) GetResourcesOk() ([]GetByContractResponseHitsHitsSourceEventResources, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []GetByContractResponseHitsHitsSourceEventResources and assigns it to the Resources field.
func (o *GetByContractResponseHitsHitsSourceEvent) SetResources(v []GetByContractResponseHitsHitsSourceEventResources) {
	o.Resources = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEvent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetByContractResponseHitsHitsSourceEvent) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEvent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetByContractResponseHitsHitsSourceEvent) SetStatus(v string) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetByContractResponseHitsHitsSourceEvent) SetType(v string) {
	o.Type = &v
}

func (o GetByContractResponseHitsHitsSourceEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Param) {
		toSerialize["param"] = o.Param
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceEvent struct {
	value *GetByContractResponseHitsHitsSourceEvent
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceEvent) Get() *GetByContractResponseHitsHitsSourceEvent {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceEvent) Set(val *GetByContractResponseHitsHitsSourceEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceEvent(val *GetByContractResponseHitsHitsSourceEvent) *NullableGetByContractResponseHitsHitsSourceEvent {
	return &NullableGetByContractResponseHitsHitsSourceEvent{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
