/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourcePrincipalIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourcePrincipalIdentity{}

// GetByContractResponseHitsHitsSourcePrincipalIdentity The identity of the user who triggered the activity.
type GetByContractResponseHitsHitsSourcePrincipalIdentity struct {
	// The customer contract number.
	ContractNumber *int32 `json:"contractNumber,omitempty"`
	// The user name.
	Username *string `json:"username,omitempty"`
}

// NewGetByContractResponseHitsHitsSourcePrincipalIdentity instantiates a new GetByContractResponseHitsHitsSourcePrincipalIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourcePrincipalIdentity() *GetByContractResponseHitsHitsSourcePrincipalIdentity {
	this := GetByContractResponseHitsHitsSourcePrincipalIdentity{}

	return &this
}

// NewGetByContractResponseHitsHitsSourcePrincipalIdentityWithDefaults instantiates a new GetByContractResponseHitsHitsSourcePrincipalIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourcePrincipalIdentityWithDefaults() *GetByContractResponseHitsHitsSourcePrincipalIdentity {
	this := GetByContractResponseHitsHitsSourcePrincipalIdentity{}
	return &this
}

// GetContractNumber returns the ContractNumber field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) GetContractNumber() int32 {
	if o == nil || IsNil(o.ContractNumber) {
		var ret int32
		return ret
	}
	return *o.ContractNumber
}

// GetContractNumberOk returns a tuple with the ContractNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) GetContractNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.ContractNumber) {
		return nil, false
	}
	return o.ContractNumber, true
}

// HasContractNumber returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) HasContractNumber() bool {
	if o != nil && !IsNil(o.ContractNumber) {
		return true
	}

	return false
}

// SetContractNumber gets a reference to the given int32 and assigns it to the ContractNumber field.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) SetContractNumber(v int32) {
	o.ContractNumber = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetByContractResponseHitsHitsSourcePrincipalIdentity) SetUsername(v string) {
	o.Username = &v
}

func (o GetByContractResponseHitsHitsSourcePrincipalIdentity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourcePrincipalIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContractNumber) {
		toSerialize["contractNumber"] = o.ContractNumber
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourcePrincipalIdentity struct {
	value *GetByContractResponseHitsHitsSourcePrincipalIdentity
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) Get() *GetByContractResponseHitsHitsSourcePrincipalIdentity {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) Set(val *GetByContractResponseHitsHitsSourcePrincipalIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourcePrincipalIdentity(val *GetByContractResponseHitsHitsSourcePrincipalIdentity) *NullableGetByContractResponseHitsHitsSourcePrincipalIdentity {
	return &NullableGetByContractResponseHitsHitsSourcePrincipalIdentity{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipalIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
