/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHits{}

// GetByContractResponseHitsHits struct for GetByContractResponseHitsHits
type GetByContractResponseHitsHits struct {
	Source *GetByContractResponseHitsHitsSource `json:"_source,omitempty"`
}

// NewGetByContractResponseHitsHits instantiates a new GetByContractResponseHitsHits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHits() *GetByContractResponseHitsHits {
	this := GetByContractResponseHitsHits{}

	return &this
}

// NewGetByContractResponseHitsHitsWithDefaults instantiates a new GetByContractResponseHitsHits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsWithDefaults() *GetByContractResponseHitsHits {
	this := GetByContractResponseHitsHits{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHits) GetSource() GetByContractResponseHitsHitsSource {
	if o == nil || IsNil(o.Source) {
		var ret GetByContractResponseHitsHitsSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHits) GetSourceOk() (*GetByContractResponseHitsHitsSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHits) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given GetByContractResponseHitsHitsSource and assigns it to the Source field.
func (o *GetByContractResponseHitsHits) SetSource(v GetByContractResponseHitsHitsSource) {
	o.Source = &v
}

func (o GetByContractResponseHitsHits) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHits struct {
	value *GetByContractResponseHitsHits
	isSet bool
}

func (v NullableGetByContractResponseHitsHits) Get() *GetByContractResponseHitsHits {
	return v.value
}

func (v *NullableGetByContractResponseHitsHits) Set(val *GetByContractResponseHitsHits) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHits) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHits(val *GetByContractResponseHitsHits) *NullableGetByContractResponseHitsHits {
	return &NullableGetByContractResponseHitsHits{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
