/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceEventParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceEventParam{}

// GetByContractResponseHitsHitsSourceEventParam Additional parameters for the given `type` of activity event.
type GetByContractResponseHitsHitsSourceEventParam struct {
	// HTTP protocol method used to trigger the activity.
	Action *string                                             `json:"action,omitempty"`
	Error  *GetByContractResponseHitsHitsSourceEventParamError `json:"error,omitempty"`
	// HTTP URI for the given activity request.
	Uri *string `json:"uri,omitempty"`
	// Component which initiated the activity. Usually equivalent to sourceService in the **principal** section.
	Initiator *string `json:"initiator,omitempty"`
	// Internal error code generated by the given activity.
	ErrorCode *string `json:"errorCode,omitempty"`
	// The IONOS service in which the activity took place.  Example values are `PUBLIC_REST` for the CloudAPI or `Provisioning` for events happening during the asynchronous resource provisioning process.
	SourceService *string `json:"sourceService,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceEventParam instantiates a new GetByContractResponseHitsHitsSourceEventParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceEventParam() *GetByContractResponseHitsHitsSourceEventParam {
	this := GetByContractResponseHitsHitsSourceEventParam{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceEventParamWithDefaults instantiates a new GetByContractResponseHitsHitsSourceEventParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceEventParamWithDefaults() *GetByContractResponseHitsHitsSourceEventParam {
	this := GetByContractResponseHitsHitsSourceEventParam{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetAction(v string) {
	o.Action = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetError() GetByContractResponseHitsHitsSourceEventParamError {
	if o == nil || IsNil(o.Error) {
		var ret GetByContractResponseHitsHitsSourceEventParamError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetErrorOk() (*GetByContractResponseHitsHitsSourceEventParamError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given GetByContractResponseHitsHitsSourceEventParamError and assigns it to the Error field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetError(v GetByContractResponseHitsHitsSourceEventParamError) {
	o.Error = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetUri(v string) {
	o.Uri = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetInitiator() string {
	if o == nil || IsNil(o.Initiator) {
		var ret string
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetInitiatorOk() (*string, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given string and assigns it to the Initiator field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetInitiator(v string) {
	o.Initiator = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetSourceService returns the SourceService field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetSourceService() string {
	if o == nil || IsNil(o.SourceService) {
		var ret string
		return ret
	}
	return *o.SourceService
}

// GetSourceServiceOk returns a tuple with the SourceService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) GetSourceServiceOk() (*string, bool) {
	if o == nil || IsNil(o.SourceService) {
		return nil, false
	}
	return o.SourceService, true
}

// HasSourceService returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParam) HasSourceService() bool {
	if o != nil && !IsNil(o.SourceService) {
		return true
	}

	return false
}

// SetSourceService gets a reference to the given string and assigns it to the SourceService field.
func (o *GetByContractResponseHitsHitsSourceEventParam) SetSourceService(v string) {
	o.SourceService = &v
}

func (o GetByContractResponseHitsHitsSourceEventParam) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceEventParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.SourceService) {
		toSerialize["sourceService"] = o.SourceService
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceEventParam struct {
	value *GetByContractResponseHitsHitsSourceEventParam
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceEventParam) Get() *GetByContractResponseHitsHitsSourceEventParam {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParam) Set(val *GetByContractResponseHitsHitsSourceEventParam) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceEventParam) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceEventParam(val *GetByContractResponseHitsHitsSourceEventParam) *NullableGetByContractResponseHitsHitsSourceEventParam {
	return &NullableGetByContractResponseHitsHitsSourceEventParam{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceEventParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
