/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourcePrincipal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourcePrincipal{}

// GetByContractResponseHitsHitsSourcePrincipal The person or process which triggered the event.
type GetByContractResponseHitsHitsSourcePrincipal struct {
	// The remote IP address which triggered the activity.
	SourceIP *string                                               `json:"sourceIP,omitempty"`
	Identity *GetByContractResponseHitsHitsSourcePrincipalIdentity `json:"identity,omitempty"`
	// The principal triggered the activity using this IONOS service.  Example values are  * `PUBLIC_REST_V6` for the CloudAPI V6, * `Reseller_V1` for the Reseller API V1 or * `DCD` for the Data Center Designer.
	SourceService *string `json:"sourceService,omitempty"`
	// The FQDN of the hostname on which the service runs.
	ServiceHost *string `json:"serviceHost,omitempty"`
}

// NewGetByContractResponseHitsHitsSourcePrincipal instantiates a new GetByContractResponseHitsHitsSourcePrincipal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourcePrincipal() *GetByContractResponseHitsHitsSourcePrincipal {
	this := GetByContractResponseHitsHitsSourcePrincipal{}

	return &this
}

// NewGetByContractResponseHitsHitsSourcePrincipalWithDefaults instantiates a new GetByContractResponseHitsHitsSourcePrincipal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourcePrincipalWithDefaults() *GetByContractResponseHitsHitsSourcePrincipal {
	this := GetByContractResponseHitsHitsSourcePrincipal{}
	return &this
}

// GetSourceIP returns the SourceIP field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetSourceIP() string {
	if o == nil || IsNil(o.SourceIP) {
		var ret string
		return ret
	}
	return *o.SourceIP
}

// GetSourceIPOk returns a tuple with the SourceIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetSourceIPOk() (*string, bool) {
	if o == nil || IsNil(o.SourceIP) {
		return nil, false
	}
	return o.SourceIP, true
}

// HasSourceIP returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) HasSourceIP() bool {
	if o != nil && !IsNil(o.SourceIP) {
		return true
	}

	return false
}

// SetSourceIP gets a reference to the given string and assigns it to the SourceIP field.
func (o *GetByContractResponseHitsHitsSourcePrincipal) SetSourceIP(v string) {
	o.SourceIP = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetIdentity() GetByContractResponseHitsHitsSourcePrincipalIdentity {
	if o == nil || IsNil(o.Identity) {
		var ret GetByContractResponseHitsHitsSourcePrincipalIdentity
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetIdentityOk() (*GetByContractResponseHitsHitsSourcePrincipalIdentity, bool) {
	if o == nil || IsNil(o.Identity) {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) HasIdentity() bool {
	if o != nil && !IsNil(o.Identity) {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given GetByContractResponseHitsHitsSourcePrincipalIdentity and assigns it to the Identity field.
func (o *GetByContractResponseHitsHitsSourcePrincipal) SetIdentity(v GetByContractResponseHitsHitsSourcePrincipalIdentity) {
	o.Identity = &v
}

// GetSourceService returns the SourceService field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetSourceService() string {
	if o == nil || IsNil(o.SourceService) {
		var ret string
		return ret
	}
	return *o.SourceService
}

// GetSourceServiceOk returns a tuple with the SourceService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetSourceServiceOk() (*string, bool) {
	if o == nil || IsNil(o.SourceService) {
		return nil, false
	}
	return o.SourceService, true
}

// HasSourceService returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) HasSourceService() bool {
	if o != nil && !IsNil(o.SourceService) {
		return true
	}

	return false
}

// SetSourceService gets a reference to the given string and assigns it to the SourceService field.
func (o *GetByContractResponseHitsHitsSourcePrincipal) SetSourceService(v string) {
	o.SourceService = &v
}

// GetServiceHost returns the ServiceHost field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetServiceHost() string {
	if o == nil || IsNil(o.ServiceHost) {
		var ret string
		return ret
	}
	return *o.ServiceHost
}

// GetServiceHostOk returns a tuple with the ServiceHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) GetServiceHostOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceHost) {
		return nil, false
	}
	return o.ServiceHost, true
}

// HasServiceHost returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourcePrincipal) HasServiceHost() bool {
	if o != nil && !IsNil(o.ServiceHost) {
		return true
	}

	return false
}

// SetServiceHost gets a reference to the given string and assigns it to the ServiceHost field.
func (o *GetByContractResponseHitsHitsSourcePrincipal) SetServiceHost(v string) {
	o.ServiceHost = &v
}

func (o GetByContractResponseHitsHitsSourcePrincipal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourcePrincipal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceIP) {
		toSerialize["sourceIP"] = o.SourceIP
	}
	if !IsNil(o.Identity) {
		toSerialize["identity"] = o.Identity
	}
	if !IsNil(o.SourceService) {
		toSerialize["sourceService"] = o.SourceService
	}
	if !IsNil(o.ServiceHost) {
		toSerialize["serviceHost"] = o.ServiceHost
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourcePrincipal struct {
	value *GetByContractResponseHitsHitsSourcePrincipal
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipal) Get() *GetByContractResponseHitsHitsSourcePrincipal {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipal) Set(val *GetByContractResponseHitsHitsSourcePrincipal) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourcePrincipal(val *GetByContractResponseHitsHitsSourcePrincipal) *NullableGetByContractResponseHitsHitsSourcePrincipal {
	return &NullableGetByContractResponseHitsHitsSourcePrincipal{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourcePrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourcePrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
