/*
 * Activity Log Service API
 *
 * The Activity Log API allows contract owners and administrators to discover what activity has happened under a specific contract. This allows auditing of user activities as well as changes to any resources. The activity is grouped by contract and can be refined using date ranges. Activity information is READ-ONLY so all calls made against the Activity Log API will be handled using GET requests.
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package activitylog

import (
	"encoding/json"
)

// checks if the GetByContractResponseHitsHitsSourceEventParamErrorMessages type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetByContractResponseHitsHitsSourceEventParamErrorMessages{}

// GetByContractResponseHitsHitsSourceEventParamErrorMessages struct for GetByContractResponseHitsHitsSourceEventParamErrorMessages
type GetByContractResponseHitsHitsSourceEventParamErrorMessages struct {
	// Internal error code generated by the given activity.
	ErrorCode *string `json:"errorCode,omitempty"`
	// Details of the specific error generated by the given activity.
	Message *string `json:"message,omitempty"`
}

// NewGetByContractResponseHitsHitsSourceEventParamErrorMessages instantiates a new GetByContractResponseHitsHitsSourceEventParamErrorMessages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetByContractResponseHitsHitsSourceEventParamErrorMessages() *GetByContractResponseHitsHitsSourceEventParamErrorMessages {
	this := GetByContractResponseHitsHitsSourceEventParamErrorMessages{}

	return &this
}

// NewGetByContractResponseHitsHitsSourceEventParamErrorMessagesWithDefaults instantiates a new GetByContractResponseHitsHitsSourceEventParamErrorMessages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetByContractResponseHitsHitsSourceEventParamErrorMessagesWithDefaults() *GetByContractResponseHitsHitsSourceEventParamErrorMessages {
	this := GetByContractResponseHitsHitsSourceEventParamErrorMessages{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetByContractResponseHitsHitsSourceEventParamErrorMessages) SetMessage(v string) {
	o.Message = &v
}

func (o GetByContractResponseHitsHitsSourceEventParamErrorMessages) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetByContractResponseHitsHitsSourceEventParamErrorMessages) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages struct {
	value *GetByContractResponseHitsHitsSourceEventParamErrorMessages
	isSet bool
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) Get() *GetByContractResponseHitsHitsSourceEventParamErrorMessages {
	return v.value
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) Set(val *GetByContractResponseHitsHitsSourceEventParamErrorMessages) {
	v.value = val
	v.isSet = true
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) IsSet() bool {
	return v.isSet
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetByContractResponseHitsHitsSourceEventParamErrorMessages(val *GetByContractResponseHitsHitsSourceEventParamErrorMessages) *NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages {
	return &NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages{value: val, isSet: true}
}

func (v NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetByContractResponseHitsHitsSourceEventParamErrorMessages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
