/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the UtilizationDailyFindByDate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UtilizationDailyFindByDate200Response{}

// UtilizationDailyFindByDate200Response struct for UtilizationDailyFindByDate200Response
type UtilizationDailyFindByDate200Response struct {
	StartDate   *string                 `json:"startDate,omitempty"`
	EndDate     *string                 `json:"endDate,omitempty"`
	Datacenters []UtilizationDataCenter `json:"datacenters,omitempty"`
	Metadata    *Metadata               `json:"metadata,omitempty"`
}

// NewUtilizationDailyFindByDate200Response instantiates a new UtilizationDailyFindByDate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilizationDailyFindByDate200Response() *UtilizationDailyFindByDate200Response {
	this := UtilizationDailyFindByDate200Response{}

	return &this
}

// NewUtilizationDailyFindByDate200ResponseWithDefaults instantiates a new UtilizationDailyFindByDate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilizationDailyFindByDate200ResponseWithDefaults() *UtilizationDailyFindByDate200Response {
	this := UtilizationDailyFindByDate200Response{}
	return &this
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *UtilizationDailyFindByDate200Response) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDailyFindByDate200Response) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *UtilizationDailyFindByDate200Response) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *UtilizationDailyFindByDate200Response) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *UtilizationDailyFindByDate200Response) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDailyFindByDate200Response) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *UtilizationDailyFindByDate200Response) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *UtilizationDailyFindByDate200Response) SetEndDate(v string) {
	o.EndDate = &v
}

// GetDatacenters returns the Datacenters field value if set, zero value otherwise.
func (o *UtilizationDailyFindByDate200Response) GetDatacenters() []UtilizationDataCenter {
	if o == nil || IsNil(o.Datacenters) {
		var ret []UtilizationDataCenter
		return ret
	}
	return o.Datacenters
}

// GetDatacentersOk returns a tuple with the Datacenters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDailyFindByDate200Response) GetDatacentersOk() ([]UtilizationDataCenter, bool) {
	if o == nil || IsNil(o.Datacenters) {
		return nil, false
	}
	return o.Datacenters, true
}

// HasDatacenters returns a boolean if a field has been set.
func (o *UtilizationDailyFindByDate200Response) HasDatacenters() bool {
	if o != nil && !IsNil(o.Datacenters) {
		return true
	}

	return false
}

// SetDatacenters gets a reference to the given []UtilizationDataCenter and assigns it to the Datacenters field.
func (o *UtilizationDailyFindByDate200Response) SetDatacenters(v []UtilizationDataCenter) {
	o.Datacenters = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UtilizationDailyFindByDate200Response) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDailyFindByDate200Response) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UtilizationDailyFindByDate200Response) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *UtilizationDailyFindByDate200Response) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o UtilizationDailyFindByDate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UtilizationDailyFindByDate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.Datacenters) {
		toSerialize["datacenters"] = o.Datacenters
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableUtilizationDailyFindByDate200Response struct {
	value *UtilizationDailyFindByDate200Response
	isSet bool
}

func (v NullableUtilizationDailyFindByDate200Response) Get() *UtilizationDailyFindByDate200Response {
	return v.value
}

func (v *NullableUtilizationDailyFindByDate200Response) Set(val *UtilizationDailyFindByDate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilizationDailyFindByDate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilizationDailyFindByDate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilizationDailyFindByDate200Response(val *UtilizationDailyFindByDate200Response) *NullableUtilizationDailyFindByDate200Response {
	return &NullableUtilizationDailyFindByDate200Response{value: val, isSet: true}
}

func (v NullableUtilizationDailyFindByDate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilizationDailyFindByDate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
