/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the Product type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Product{}

// Product struct for Product
type Product struct {
	// Product code (just active will be provided)
	MeterId *string `json:"meterId,omitempty"`
	// Product description (human readable)
	MeterDesc *string `json:"meterDesc,omitempty"`
	// The flag specifies whether the product is marked as deprecated
	Deprecated *bool `json:"deprecated,omitempty"`
	// The unit applied for the product during computation
	Unit *string `json:"unit,omitempty"`
	// type of the billing (consumption-based or commitment-based)
	Type *string `json:"type,omitempty"`
	// length of the commitment period (only provided for commitment items) in months
	Term     NullableInt32           `json:"term,omitempty"`
	UnitCost NullableProductUnitCost `json:"unitCost,omitempty"`
}

// NewProduct instantiates a new Product object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct() *Product {
	this := Product{}

	return &this
}

// NewProductWithDefaults instantiates a new Product object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductWithDefaults() *Product {
	this := Product{}
	return &this
}

// GetMeterId returns the MeterId field value if set, zero value otherwise.
func (o *Product) GetMeterId() string {
	if o == nil || IsNil(o.MeterId) {
		var ret string
		return ret
	}
	return *o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetMeterIdOk() (*string, bool) {
	if o == nil || IsNil(o.MeterId) {
		return nil, false
	}
	return o.MeterId, true
}

// HasMeterId returns a boolean if a field has been set.
func (o *Product) HasMeterId() bool {
	if o != nil && !IsNil(o.MeterId) {
		return true
	}

	return false
}

// SetMeterId gets a reference to the given string and assigns it to the MeterId field.
func (o *Product) SetMeterId(v string) {
	o.MeterId = &v
}

// GetMeterDesc returns the MeterDesc field value if set, zero value otherwise.
func (o *Product) GetMeterDesc() string {
	if o == nil || IsNil(o.MeterDesc) {
		var ret string
		return ret
	}
	return *o.MeterDesc
}

// GetMeterDescOk returns a tuple with the MeterDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetMeterDescOk() (*string, bool) {
	if o == nil || IsNil(o.MeterDesc) {
		return nil, false
	}
	return o.MeterDesc, true
}

// HasMeterDesc returns a boolean if a field has been set.
func (o *Product) HasMeterDesc() bool {
	if o != nil && !IsNil(o.MeterDesc) {
		return true
	}

	return false
}

// SetMeterDesc gets a reference to the given string and assigns it to the MeterDesc field.
func (o *Product) SetMeterDesc(v string) {
	o.MeterDesc = &v
}

// GetDeprecated returns the Deprecated field value if set, zero value otherwise.
func (o *Product) GetDeprecated() bool {
	if o == nil || IsNil(o.Deprecated) {
		var ret bool
		return ret
	}
	return *o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetDeprecatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deprecated) {
		return nil, false
	}
	return o.Deprecated, true
}

// HasDeprecated returns a boolean if a field has been set.
func (o *Product) HasDeprecated() bool {
	if o != nil && !IsNil(o.Deprecated) {
		return true
	}

	return false
}

// SetDeprecated gets a reference to the given bool and assigns it to the Deprecated field.
func (o *Product) SetDeprecated(v bool) {
	o.Deprecated = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *Product) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *Product) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *Product) SetUnit(v string) {
	o.Unit = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Product) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Product) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Product) SetType(v string) {
	o.Type = &v
}

// GetTerm returns the Term field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Product) GetTerm() int32 {
	if o == nil || IsNil(o.Term.Get()) {
		var ret int32
		return ret
	}
	return *o.Term.Get()
}

// GetTermOk returns a tuple with the Term field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Product) GetTermOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Term.Get(), o.Term.IsSet()
}

// HasTerm returns a boolean if a field has been set.
func (o *Product) HasTerm() bool {
	if o != nil && o.Term.IsSet() {
		return true
	}

	return false
}

// SetTerm gets a reference to the given NullableInt32 and assigns it to the Term field.
func (o *Product) SetTerm(v int32) {
	o.Term.Set(&v)
}

// SetTermNil sets the value for Term to be an explicit nil
func (o *Product) SetTermNil() {
	o.Term.Set(nil)
}

// UnsetTerm ensures that no value is present for Term, not even an explicit nil
func (o *Product) UnsetTerm() {
	o.Term.Unset()
}

// GetUnitCost returns the UnitCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Product) GetUnitCost() ProductUnitCost {
	if o == nil || IsNil(o.UnitCost.Get()) {
		var ret ProductUnitCost
		return ret
	}
	return *o.UnitCost.Get()
}

// GetUnitCostOk returns a tuple with the UnitCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Product) GetUnitCostOk() (*ProductUnitCost, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitCost.Get(), o.UnitCost.IsSet()
}

// HasUnitCost returns a boolean if a field has been set.
func (o *Product) HasUnitCost() bool {
	if o != nil && o.UnitCost.IsSet() {
		return true
	}

	return false
}

// SetUnitCost gets a reference to the given NullableProductUnitCost and assigns it to the UnitCost field.
func (o *Product) SetUnitCost(v ProductUnitCost) {
	o.UnitCost.Set(&v)
}

// SetUnitCostNil sets the value for UnitCost to be an explicit nil
func (o *Product) SetUnitCostNil() {
	o.UnitCost.Set(nil)
}

// UnsetUnitCost ensures that no value is present for UnitCost, not even an explicit nil
func (o *Product) UnsetUnitCost() {
	o.UnitCost.Unset()
}

func (o Product) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Product) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MeterId) {
		toSerialize["meterId"] = o.MeterId
	}
	if !IsNil(o.MeterDesc) {
		toSerialize["meterDesc"] = o.MeterDesc
	}
	if !IsNil(o.Deprecated) {
		toSerialize["deprecated"] = o.Deprecated
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Term.IsSet() {
		toSerialize["term"] = o.Term.Get()
	}
	if o.UnitCost.IsSet() {
		toSerialize["unitCost"] = o.UnitCost.Get()
	}
	return toSerialize, nil
}

type NullableProduct struct {
	value *Product
	isSet bool
}

func (v NullableProduct) Get() *Product {
	return v.value
}

func (v *NullableProduct) Set(val *Product) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct(val *Product) *NullableProduct {
	return &NullableProduct{value: val, isSet: true}
}

func (v NullableProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
