/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoicesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicesGet200Response{}

// InvoicesGet200Response struct for InvoicesGet200Response
type InvoicesGet200Response struct {
	Metadata *Metadata                        `json:"metadata,omitempty"`
	Invoices []InvoicesGet200ResponseInvoices `json:"invoices,omitempty"`
}

// NewInvoicesGet200Response instantiates a new InvoicesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicesGet200Response() *InvoicesGet200Response {
	this := InvoicesGet200Response{}

	return &this
}

// NewInvoicesGet200ResponseWithDefaults instantiates a new InvoicesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicesGet200ResponseWithDefaults() *InvoicesGet200Response {
	this := InvoicesGet200Response{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *InvoicesGet200Response) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesGet200Response) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *InvoicesGet200Response) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *InvoicesGet200Response) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *InvoicesGet200Response) GetInvoices() []InvoicesGet200ResponseInvoices {
	if o == nil || IsNil(o.Invoices) {
		var ret []InvoicesGet200ResponseInvoices
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesGet200Response) GetInvoicesOk() ([]InvoicesGet200ResponseInvoices, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *InvoicesGet200Response) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []InvoicesGet200ResponseInvoices and assigns it to the Invoices field.
func (o *InvoicesGet200Response) SetInvoices(v []InvoicesGet200ResponseInvoices) {
	o.Invoices = v
}

func (o InvoicesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	return toSerialize, nil
}

type NullableInvoicesGet200Response struct {
	value *InvoicesGet200Response
	isSet bool
}

func (v NullableInvoicesGet200Response) Get() *InvoicesGet200Response {
	return v.value
}

func (v *NullableInvoicesGet200Response) Set(val *InvoicesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicesGet200Response(val *InvoicesGet200Response) *NullableInvoicesGet200Response {
	return &NullableInvoicesGet200Response{value: val, isSet: true}
}

func (v NullableInvoicesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
