/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoicesGet200ResponseInvoices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicesGet200ResponseInvoices{}

// InvoicesGet200ResponseInvoices struct for InvoicesGet200ResponseInvoices
type InvoicesGet200ResponseInvoices struct {
	Id     *string         `json:"id,omitempty"`
	Date   *string         `json:"date,omitempty"`
	Amount NullableFloat32 `json:"amount,omitempty"`
	Unit   NullableString  `json:"unit,omitempty"`
}

// NewInvoicesGet200ResponseInvoices instantiates a new InvoicesGet200ResponseInvoices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicesGet200ResponseInvoices() *InvoicesGet200ResponseInvoices {
	this := InvoicesGet200ResponseInvoices{}

	return &this
}

// NewInvoicesGet200ResponseInvoicesWithDefaults instantiates a new InvoicesGet200ResponseInvoices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicesGet200ResponseInvoicesWithDefaults() *InvoicesGet200ResponseInvoices {
	this := InvoicesGet200ResponseInvoices{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InvoicesGet200ResponseInvoices) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesGet200ResponseInvoices) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InvoicesGet200ResponseInvoices) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InvoicesGet200ResponseInvoices) SetId(v string) {
	o.Id = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *InvoicesGet200ResponseInvoices) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesGet200ResponseInvoices) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *InvoicesGet200ResponseInvoices) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *InvoicesGet200ResponseInvoices) SetDate(v string) {
	o.Date = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoicesGet200ResponseInvoices) GetAmount() float32 {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret float32
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoicesGet200ResponseInvoices) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *InvoicesGet200ResponseInvoices) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableFloat32 and assigns it to the Amount field.
func (o *InvoicesGet200ResponseInvoices) SetAmount(v float32) {
	o.Amount.Set(&v)
}

// SetAmountNil sets the value for Amount to be an explicit nil
func (o *InvoicesGet200ResponseInvoices) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *InvoicesGet200ResponseInvoices) UnsetAmount() {
	o.Amount.Unset()
}

// GetUnit returns the Unit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoicesGet200ResponseInvoices) GetUnit() string {
	if o == nil || IsNil(o.Unit.Get()) {
		var ret string
		return ret
	}
	return *o.Unit.Get()
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoicesGet200ResponseInvoices) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unit.Get(), o.Unit.IsSet()
}

// HasUnit returns a boolean if a field has been set.
func (o *InvoicesGet200ResponseInvoices) HasUnit() bool {
	if o != nil && o.Unit.IsSet() {
		return true
	}

	return false
}

// SetUnit gets a reference to the given NullableString and assigns it to the Unit field.
func (o *InvoicesGet200ResponseInvoices) SetUnit(v string) {
	o.Unit.Set(&v)
}

// SetUnitNil sets the value for Unit to be an explicit nil
func (o *InvoicesGet200ResponseInvoices) SetUnitNil() {
	o.Unit.Set(nil)
}

// UnsetUnit ensures that no value is present for Unit, not even an explicit nil
func (o *InvoicesGet200ResponseInvoices) UnsetUnit() {
	o.Unit.Unset()
}

func (o InvoicesGet200ResponseInvoices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicesGet200ResponseInvoices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if o.Unit.IsSet() {
		toSerialize["unit"] = o.Unit.Get()
	}
	return toSerialize, nil
}

type NullableInvoicesGet200ResponseInvoices struct {
	value *InvoicesGet200ResponseInvoices
	isSet bool
}

func (v NullableInvoicesGet200ResponseInvoices) Get() *InvoicesGet200ResponseInvoices {
	return v.value
}

func (v *NullableInvoicesGet200ResponseInvoices) Set(val *InvoicesGet200ResponseInvoices) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicesGet200ResponseInvoices) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicesGet200ResponseInvoices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicesGet200ResponseInvoices(val *InvoicesGet200ResponseInvoices) *NullableInvoicesGet200ResponseInvoices {
	return &NullableInvoicesGet200ResponseInvoices{value: val, isSet: true}
}

func (v NullableInvoicesGet200ResponseInvoices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicesGet200ResponseInvoices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
