/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"

	"fmt"
)

// ResourceType the model 'ResourceType'
type ResourceType string

// List of ResourceType
const (
	RESOURCETYPE_SERVER             ResourceType = "SERVER"
	RESOURCETYPE_STORAGE            ResourceType = "STORAGE"
	RESOURCETYPE_SNAPSHOT           ResourceType = "SNAPSHOT"
	RESOURCETYPE_NATGATEWAY         ResourceType = "NATGATEWAY"
	RESOURCETYPE_NIC                ResourceType = "NIC"
	RESOURCETYPE_IP                 ResourceType = "IP"
	RESOURCETYPE_IP_ADDRESS         ResourceType = "IP_ADDRESS"
	RESOURCETYPE_CUBETEMPLATE       ResourceType = "CUBETEMPLATE"
	RESOURCETYPE_LOADBALANCER       ResourceType = "LOADBALANCER"
	RESOURCETYPE_BACKUP             ResourceType = "BACKUP"
	RESOURCETYPE_S3                 ResourceType = "S3"
	RESOURCETYPE_TRAFFIC            ResourceType = "TRAFFIC"
	RESOURCETYPE_DB                 ResourceType = "DB"
	RESOURCETYPE_BMC                ResourceType = "BMC"
	RESOURCETYPE_DBAAS              ResourceType = "DBAAS"
	RESOURCETYPE_CRAAS              ResourceType = "CRAAS"
	RESOURCETYPE_LAAS               ResourceType = "LAAS"
	RESOURCETYPE_DSAAS              ResourceType = "DSAAS"
	RESOURCETYPE_DNS                ResourceType = "DNS"
	RESOURCETYPE_MONITORING         ResourceType = "MONITORING"
	RESOURCETYPE_KAFKA              ResourceType = "KAFKA"
	RESOURCETYPE_VPN                ResourceType = "VPN"
	RESOURCETYPE_VPNGATEWAY         ResourceType = "VPNGATEWAY"
	RESOURCETYPE_CONTAINERREGISTRY  ResourceType = "CONTAINERREGISTRY"
	RESOURCETYPE_NETWORKFILESTORAGE ResourceType = "NETWORKFILESTORAGE"
	RESOURCETYPE_MARIADB            ResourceType = "MARIADB"
	RESOURCETYPE_INMEMORYDB         ResourceType = "INMEMORYDB"
	RESOURCETYPE_CDN                ResourceType = "CDN"
	RESOURCETYPE_OBJECTSTORAGE      ResourceType = "OBJECTSTORAGE"
	RESOURCETYPE_APIGATEWAY         ResourceType = "APIGATEWAY"
	RESOURCETYPE_NATLB              ResourceType = "NATLB"
)

func (v *ResourceType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceType(value)
	for _, existing := range []ResourceType{"SERVER", "STORAGE", "SNAPSHOT", "NATGATEWAY", "NIC", "IP", "IP_ADDRESS", "CUBETEMPLATE", "LOADBALANCER", "BACKUP", "S3", "TRAFFIC", "DB", "BMC", "DBAAS", "CRAAS", "LAAS", "DSAAS", "DNS", "MONITORING", "KAFKA", "VPN", "VPNGATEWAY", "CONTAINERREGISTRY", "NETWORKFILESTORAGE", "MARIADB", "INMEMORYDB", "CDN", "OBJECTSTORAGE", "APIGATEWAY", "NATLB"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResourceType", value)
}

// Ptr returns reference to ResourceType value
func (v ResourceType) Ptr() *ResourceType {
	return &v
}

type NullableResourceType struct {
	value *ResourceType
	isSet bool
}

func (v NullableResourceType) Get() *ResourceType {
	return v.value
}

func (v *NullableResourceType) Set(val *ResourceType) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceType) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceType(val *ResourceType) *NullableResourceType {
	return &NullableResourceType{value: val, isSet: true}
}

func (v NullableResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
