/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the ProductUnitCost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUnitCost{}

// ProductUnitCost struct for ProductUnitCost
type ProductUnitCost struct {
	Quantity *string `json:"quantity,omitempty"`
	Unit     *string `json:"unit,omitempty"`
}

// NewProductUnitCost instantiates a new ProductUnitCost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUnitCost() *ProductUnitCost {
	this := ProductUnitCost{}

	return &this
}

// NewProductUnitCostWithDefaults instantiates a new ProductUnitCost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUnitCostWithDefaults() *ProductUnitCost {
	this := ProductUnitCost{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ProductUnitCost) GetQuantity() string {
	if o == nil || IsNil(o.Quantity) {
		var ret string
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUnitCost) GetQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ProductUnitCost) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given string and assigns it to the Quantity field.
func (o *ProductUnitCost) SetQuantity(v string) {
	o.Quantity = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ProductUnitCost) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUnitCost) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ProductUnitCost) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *ProductUnitCost) SetUnit(v string) {
	o.Unit = &v
}

func (o ProductUnitCost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUnitCost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableProductUnitCost struct {
	value *ProductUnitCost
	isSet bool
}

func (v NullableProductUnitCost) Get() *ProductUnitCost {
	return v.value
}

func (v *NullableProductUnitCost) Set(val *ProductUnitCost) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUnitCost) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUnitCost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUnitCost(val *ProductUnitCost) *NullableProductUnitCost {
	return &NullableProductUnitCost{value: val, isSet: true}
}

func (v NullableProductUnitCost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUnitCost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
