/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficMetadata{}

// TrafficMetadata struct for TrafficMetadata
type TrafficMetadata struct {
	ContractId *string        `json:"contractId,omitempty"`
	CustomerId *string        `json:"customerId,omitempty"`
	Reference  NullableString `json:"reference,omitempty"`
	Period     *string        `json:"period,omitempty"`
	Unit       *string        `json:"unit,omitempty"`
}

// NewTrafficMetadata instantiates a new TrafficMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficMetadata() *TrafficMetadata {
	this := TrafficMetadata{}

	return &this
}

// NewTrafficMetadataWithDefaults instantiates a new TrafficMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficMetadataWithDefaults() *TrafficMetadata {
	this := TrafficMetadata{}
	return &this
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *TrafficMetadata) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadata) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *TrafficMetadata) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *TrafficMetadata) SetContractId(v string) {
	o.ContractId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *TrafficMetadata) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadata) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *TrafficMetadata) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *TrafficMetadata) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetReference returns the Reference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrafficMetadata) GetReference() string {
	if o == nil || IsNil(o.Reference.Get()) {
		var ret string
		return ret
	}
	return *o.Reference.Get()
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrafficMetadata) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reference.Get(), o.Reference.IsSet()
}

// HasReference returns a boolean if a field has been set.
func (o *TrafficMetadata) HasReference() bool {
	if o != nil && o.Reference.IsSet() {
		return true
	}

	return false
}

// SetReference gets a reference to the given NullableString and assigns it to the Reference field.
func (o *TrafficMetadata) SetReference(v string) {
	o.Reference.Set(&v)
}

// SetReferenceNil sets the value for Reference to be an explicit nil
func (o *TrafficMetadata) SetReferenceNil() {
	o.Reference.Set(nil)
}

// UnsetReference ensures that no value is present for Reference, not even an explicit nil
func (o *TrafficMetadata) UnsetReference() {
	o.Reference.Unset()
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *TrafficMetadata) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadata) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *TrafficMetadata) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *TrafficMetadata) SetPeriod(v string) {
	o.Period = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *TrafficMetadata) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadata) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *TrafficMetadata) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *TrafficMetadata) SetUnit(v string) {
	o.Unit = &v
}

func (o TrafficMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContractId) {
		toSerialize["contractId"] = o.ContractId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if o.Reference.IsSet() {
		toSerialize["reference"] = o.Reference.Get()
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableTrafficMetadata struct {
	value *TrafficMetadata
	isSet bool
}

func (v NullableTrafficMetadata) Get() *TrafficMetadata {
	return v.value
}

func (v *NullableTrafficMetadata) Set(val *TrafficMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficMetadata(val *TrafficMetadata) *NullableTrafficMetadata {
	return &NullableTrafficMetadata{value: val, isSet: true}
}

func (v NullableTrafficMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
