/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficMetadataAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficMetadataAllOf{}

// TrafficMetadataAllOf struct for TrafficMetadataAllOf
type TrafficMetadataAllOf struct {
	Period *string `json:"period,omitempty"`
	Unit   *string `json:"unit,omitempty"`
}

// NewTrafficMetadataAllOf instantiates a new TrafficMetadataAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficMetadataAllOf() *TrafficMetadataAllOf {
	this := TrafficMetadataAllOf{}

	return &this
}

// NewTrafficMetadataAllOfWithDefaults instantiates a new TrafficMetadataAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficMetadataAllOfWithDefaults() *TrafficMetadataAllOf {
	this := TrafficMetadataAllOf{}
	return &this
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *TrafficMetadataAllOf) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadataAllOf) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *TrafficMetadataAllOf) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *TrafficMetadataAllOf) SetPeriod(v string) {
	o.Period = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *TrafficMetadataAllOf) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficMetadataAllOf) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *TrafficMetadataAllOf) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *TrafficMetadataAllOf) SetUnit(v string) {
	o.Unit = &v
}

func (o TrafficMetadataAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficMetadataAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableTrafficMetadataAllOf struct {
	value *TrafficMetadataAllOf
	isSet bool
}

func (v NullableTrafficMetadataAllOf) Get() *TrafficMetadataAllOf {
	return v.value
}

func (v *NullableTrafficMetadataAllOf) Set(val *TrafficMetadataAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficMetadataAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficMetadataAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficMetadataAllOf(val *TrafficMetadataAllOf) *NullableTrafficMetadataAllOf {
	return &NullableTrafficMetadataAllOf{value: val, isSet: true}
}

func (v NullableTrafficMetadataAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficMetadataAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
