/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"

	"time"
)

// checks if the UtilizationMeter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UtilizationMeter{}

// UtilizationMeter struct for UtilizationMeter
type UtilizationMeter struct {
	Id         *string                   `json:"id,omitempty"`
	ResourceId NullableString            `json:"resourceId,omitempty"`
	ServerId   NullableString            `json:"serverId,omitempty"`
	Name       *string                   `json:"name,omitempty"`
	Type       *ResourceType             `json:"type,omitempty"`
	From       *IonosTime                `json:"from,omitempty"`
	To         *IonosTime                `json:"to,omitempty"`
	Exists     NullableBool              `json:"exists,omitempty"`
	MeterId    *string                   `json:"meterId,omitempty"`
	MeterDesc  *string                   `json:"meterDesc,omitempty"`
	Region     *string                   `json:"region,omitempty"`
	Quantity   *UtilizationMeterQuantity `json:"quantity,omitempty"`
}

// NewUtilizationMeter instantiates a new UtilizationMeter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilizationMeter() *UtilizationMeter {
	this := UtilizationMeter{}

	return &this
}

// NewUtilizationMeterWithDefaults instantiates a new UtilizationMeter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilizationMeterWithDefaults() *UtilizationMeter {
	this := UtilizationMeter{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UtilizationMeter) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UtilizationMeter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UtilizationMeter) SetId(v string) {
	o.Id = &v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizationMeter) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceId.Get()
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizationMeter) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceId.Get(), o.ResourceId.IsSet()
}

// HasResourceId returns a boolean if a field has been set.
func (o *UtilizationMeter) HasResourceId() bool {
	if o != nil && o.ResourceId.IsSet() {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given NullableString and assigns it to the ResourceId field.
func (o *UtilizationMeter) SetResourceId(v string) {
	o.ResourceId.Set(&v)
}

// SetResourceIdNil sets the value for ResourceId to be an explicit nil
func (o *UtilizationMeter) SetResourceIdNil() {
	o.ResourceId.Set(nil)
}

// UnsetResourceId ensures that no value is present for ResourceId, not even an explicit nil
func (o *UtilizationMeter) UnsetResourceId() {
	o.ResourceId.Unset()
}

// GetServerId returns the ServerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizationMeter) GetServerId() string {
	if o == nil || IsNil(o.ServerId.Get()) {
		var ret string
		return ret
	}
	return *o.ServerId.Get()
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizationMeter) GetServerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServerId.Get(), o.ServerId.IsSet()
}

// HasServerId returns a boolean if a field has been set.
func (o *UtilizationMeter) HasServerId() bool {
	if o != nil && o.ServerId.IsSet() {
		return true
	}

	return false
}

// SetServerId gets a reference to the given NullableString and assigns it to the ServerId field.
func (o *UtilizationMeter) SetServerId(v string) {
	o.ServerId.Set(&v)
}

// SetServerIdNil sets the value for ServerId to be an explicit nil
func (o *UtilizationMeter) SetServerIdNil() {
	o.ServerId.Set(nil)
}

// UnsetServerId ensures that no value is present for ServerId, not even an explicit nil
func (o *UtilizationMeter) UnsetServerId() {
	o.ServerId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UtilizationMeter) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UtilizationMeter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UtilizationMeter) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UtilizationMeter) GetType() ResourceType {
	if o == nil || IsNil(o.Type) {
		var ret ResourceType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetTypeOk() (*ResourceType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UtilizationMeter) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ResourceType and assigns it to the Type field.
func (o *UtilizationMeter) SetType(v ResourceType) {
	o.Type = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *UtilizationMeter) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return o.From.Time
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return &o.From.Time, true
}

// HasFrom returns a boolean if a field has been set.
func (o *UtilizationMeter) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *UtilizationMeter) SetFrom(v time.Time) {
	o.From = &IonosTime{v}
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *UtilizationMeter) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return o.To.Time
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return &o.To.Time, true
}

// HasTo returns a boolean if a field has been set.
func (o *UtilizationMeter) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *UtilizationMeter) SetTo(v time.Time) {
	o.To = &IonosTime{v}
}

// GetExists returns the Exists field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizationMeter) GetExists() bool {
	if o == nil || IsNil(o.Exists.Get()) {
		var ret bool
		return ret
	}
	return *o.Exists.Get()
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizationMeter) GetExistsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Exists.Get(), o.Exists.IsSet()
}

// HasExists returns a boolean if a field has been set.
func (o *UtilizationMeter) HasExists() bool {
	if o != nil && o.Exists.IsSet() {
		return true
	}

	return false
}

// SetExists gets a reference to the given NullableBool and assigns it to the Exists field.
func (o *UtilizationMeter) SetExists(v bool) {
	o.Exists.Set(&v)
}

// SetExistsNil sets the value for Exists to be an explicit nil
func (o *UtilizationMeter) SetExistsNil() {
	o.Exists.Set(nil)
}

// UnsetExists ensures that no value is present for Exists, not even an explicit nil
func (o *UtilizationMeter) UnsetExists() {
	o.Exists.Unset()
}

// GetMeterId returns the MeterId field value if set, zero value otherwise.
func (o *UtilizationMeter) GetMeterId() string {
	if o == nil || IsNil(o.MeterId) {
		var ret string
		return ret
	}
	return *o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetMeterIdOk() (*string, bool) {
	if o == nil || IsNil(o.MeterId) {
		return nil, false
	}
	return o.MeterId, true
}

// HasMeterId returns a boolean if a field has been set.
func (o *UtilizationMeter) HasMeterId() bool {
	if o != nil && !IsNil(o.MeterId) {
		return true
	}

	return false
}

// SetMeterId gets a reference to the given string and assigns it to the MeterId field.
func (o *UtilizationMeter) SetMeterId(v string) {
	o.MeterId = &v
}

// GetMeterDesc returns the MeterDesc field value if set, zero value otherwise.
func (o *UtilizationMeter) GetMeterDesc() string {
	if o == nil || IsNil(o.MeterDesc) {
		var ret string
		return ret
	}
	return *o.MeterDesc
}

// GetMeterDescOk returns a tuple with the MeterDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetMeterDescOk() (*string, bool) {
	if o == nil || IsNil(o.MeterDesc) {
		return nil, false
	}
	return o.MeterDesc, true
}

// HasMeterDesc returns a boolean if a field has been set.
func (o *UtilizationMeter) HasMeterDesc() bool {
	if o != nil && !IsNil(o.MeterDesc) {
		return true
	}

	return false
}

// SetMeterDesc gets a reference to the given string and assigns it to the MeterDesc field.
func (o *UtilizationMeter) SetMeterDesc(v string) {
	o.MeterDesc = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *UtilizationMeter) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *UtilizationMeter) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *UtilizationMeter) SetRegion(v string) {
	o.Region = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *UtilizationMeter) GetQuantity() UtilizationMeterQuantity {
	if o == nil || IsNil(o.Quantity) {
		var ret UtilizationMeterQuantity
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationMeter) GetQuantityOk() (*UtilizationMeterQuantity, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *UtilizationMeter) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given UtilizationMeterQuantity and assigns it to the Quantity field.
func (o *UtilizationMeter) SetQuantity(v UtilizationMeterQuantity) {
	o.Quantity = &v
}

func (o UtilizationMeter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UtilizationMeter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.ResourceId.IsSet() {
		toSerialize["resourceId"] = o.ResourceId.Get()
	}
	if o.ServerId.IsSet() {
		toSerialize["serverId"] = o.ServerId.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if o.Exists.IsSet() {
		toSerialize["exists"] = o.Exists.Get()
	}
	if !IsNil(o.MeterId) {
		toSerialize["meterId"] = o.MeterId
	}
	if !IsNil(o.MeterDesc) {
		toSerialize["meterDesc"] = o.MeterDesc
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableUtilizationMeter struct {
	value *UtilizationMeter
	isSet bool
}

func (v NullableUtilizationMeter) Get() *UtilizationMeter {
	return v.value
}

func (v *NullableUtilizationMeter) Set(val *UtilizationMeter) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilizationMeter) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilizationMeter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilizationMeter(val *UtilizationMeter) *NullableUtilizationMeter {
	return &NullableUtilizationMeter{value: val, isSet: true}
}

func (v NullableUtilizationMeter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilizationMeter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
