/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the EvnMetadataAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvnMetadataAllOf{}

// EvnMetadataAllOf struct for EvnMetadataAllOf
type EvnMetadataAllOf struct {
	Period *string `json:"period,omitempty"`
}

// NewEvnMetadataAllOf instantiates a new EvnMetadataAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvnMetadataAllOf() *EvnMetadataAllOf {
	this := EvnMetadataAllOf{}

	return &this
}

// NewEvnMetadataAllOfWithDefaults instantiates a new EvnMetadataAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvnMetadataAllOfWithDefaults() *EvnMetadataAllOf {
	this := EvnMetadataAllOf{}
	return &this
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *EvnMetadataAllOf) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnMetadataAllOf) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *EvnMetadataAllOf) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *EvnMetadataAllOf) SetPeriod(v string) {
	o.Period = &v
}

func (o EvnMetadataAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvnMetadataAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableEvnMetadataAllOf struct {
	value *EvnMetadataAllOf
	isSet bool
}

func (v NullableEvnMetadataAllOf) Get() *EvnMetadataAllOf {
	return v.value
}

func (v *NullableEvnMetadataAllOf) Set(val *EvnMetadataAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableEvnMetadataAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableEvnMetadataAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvnMetadataAllOf(val *EvnMetadataAllOf) *NullableEvnMetadataAllOf {
	return &NullableEvnMetadataAllOf{value: val, isSet: true}
}

func (v NullableEvnMetadataAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvnMetadataAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
