/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceDatacentersRebate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceDatacentersRebate{}

// InvoiceDatacentersRebate struct for InvoiceDatacentersRebate
type InvoiceDatacentersRebate struct {
	Amount *InvoiceTotal `json:"amount,omitempty"`
}

// NewInvoiceDatacentersRebate instantiates a new InvoiceDatacentersRebate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceDatacentersRebate() *InvoiceDatacentersRebate {
	this := InvoiceDatacentersRebate{}

	return &this
}

// NewInvoiceDatacentersRebateWithDefaults instantiates a new InvoiceDatacentersRebate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceDatacentersRebateWithDefaults() *InvoiceDatacentersRebate {
	this := InvoiceDatacentersRebate{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *InvoiceDatacentersRebate) GetAmount() InvoiceTotal {
	if o == nil || IsNil(o.Amount) {
		var ret InvoiceTotal
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacentersRebate) GetAmountOk() (*InvoiceTotal, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *InvoiceDatacentersRebate) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given InvoiceTotal and assigns it to the Amount field.
func (o *InvoiceDatacentersRebate) SetAmount(v InvoiceTotal) {
	o.Amount = &v
}

func (o InvoiceDatacentersRebate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceDatacentersRebate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableInvoiceDatacentersRebate struct {
	value *InvoiceDatacentersRebate
	isSet bool
}

func (v NullableInvoiceDatacentersRebate) Get() *InvoiceDatacentersRebate {
	return v.value
}

func (v *NullableInvoiceDatacentersRebate) Set(val *InvoiceDatacentersRebate) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceDatacentersRebate) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceDatacentersRebate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceDatacentersRebate(val *InvoiceDatacentersRebate) *NullableInvoiceDatacentersRebate {
	return &NullableInvoiceDatacentersRebate{value: val, isSet: true}
}

func (v NullableInvoiceDatacentersRebate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceDatacentersRebate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
