/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceMetadata{}

// InvoiceMetadata struct for InvoiceMetadata
type InvoiceMetadata struct {
	InvoiceId     *string        `json:"invoiceId,omitempty"`
	ContractId    *string        `json:"contractId,omitempty"`
	CustomerId    *string        `json:"customerId,omitempty"`
	CreatedDate   *string        `json:"createdDate,omitempty"`
	StartDate     *string        `json:"startDate,omitempty"`
	EndDate       *string        `json:"endDate,omitempty"`
	PostingPeriod *string        `json:"postingPeriod,omitempty"`
	FinallyPosted *bool          `json:"finallyPosted,omitempty"`
	Reference     NullableString `json:"reference,omitempty"`
	// Reference text or number for the subcontract set by the reseller
	ResellerRef NullableString `json:"resellerRef,omitempty"`
}

// NewInvoiceMetadata instantiates a new InvoiceMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceMetadata() *InvoiceMetadata {
	this := InvoiceMetadata{}

	return &this
}

// NewInvoiceMetadataWithDefaults instantiates a new InvoiceMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceMetadataWithDefaults() *InvoiceMetadata {
	this := InvoiceMetadata{}
	return &this
}

// GetInvoiceId returns the InvoiceId field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetInvoiceId() string {
	if o == nil || IsNil(o.InvoiceId) {
		var ret string
		return ret
	}
	return *o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetInvoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceId) {
		return nil, false
	}
	return o.InvoiceId, true
}

// HasInvoiceId returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasInvoiceId() bool {
	if o != nil && !IsNil(o.InvoiceId) {
		return true
	}

	return false
}

// SetInvoiceId gets a reference to the given string and assigns it to the InvoiceId field.
func (o *InvoiceMetadata) SetInvoiceId(v string) {
	o.InvoiceId = &v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *InvoiceMetadata) SetContractId(v string) {
	o.ContractId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *InvoiceMetadata) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetCreatedDate() string {
	if o == nil || IsNil(o.CreatedDate) {
		var ret string
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetCreatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given string and assigns it to the CreatedDate field.
func (o *InvoiceMetadata) SetCreatedDate(v string) {
	o.CreatedDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *InvoiceMetadata) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *InvoiceMetadata) SetEndDate(v string) {
	o.EndDate = &v
}

// GetPostingPeriod returns the PostingPeriod field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetPostingPeriod() string {
	if o == nil || IsNil(o.PostingPeriod) {
		var ret string
		return ret
	}
	return *o.PostingPeriod
}

// GetPostingPeriodOk returns a tuple with the PostingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetPostingPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.PostingPeriod) {
		return nil, false
	}
	return o.PostingPeriod, true
}

// HasPostingPeriod returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasPostingPeriod() bool {
	if o != nil && !IsNil(o.PostingPeriod) {
		return true
	}

	return false
}

// SetPostingPeriod gets a reference to the given string and assigns it to the PostingPeriod field.
func (o *InvoiceMetadata) SetPostingPeriod(v string) {
	o.PostingPeriod = &v
}

// GetFinallyPosted returns the FinallyPosted field value if set, zero value otherwise.
func (o *InvoiceMetadata) GetFinallyPosted() bool {
	if o == nil || IsNil(o.FinallyPosted) {
		var ret bool
		return ret
	}
	return *o.FinallyPosted
}

// GetFinallyPostedOk returns a tuple with the FinallyPosted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMetadata) GetFinallyPostedOk() (*bool, bool) {
	if o == nil || IsNil(o.FinallyPosted) {
		return nil, false
	}
	return o.FinallyPosted, true
}

// HasFinallyPosted returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasFinallyPosted() bool {
	if o != nil && !IsNil(o.FinallyPosted) {
		return true
	}

	return false
}

// SetFinallyPosted gets a reference to the given bool and assigns it to the FinallyPosted field.
func (o *InvoiceMetadata) SetFinallyPosted(v bool) {
	o.FinallyPosted = &v
}

// GetReference returns the Reference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceMetadata) GetReference() string {
	if o == nil || IsNil(o.Reference.Get()) {
		var ret string
		return ret
	}
	return *o.Reference.Get()
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceMetadata) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reference.Get(), o.Reference.IsSet()
}

// HasReference returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasReference() bool {
	if o != nil && o.Reference.IsSet() {
		return true
	}

	return false
}

// SetReference gets a reference to the given NullableString and assigns it to the Reference field.
func (o *InvoiceMetadata) SetReference(v string) {
	o.Reference.Set(&v)
}

// SetReferenceNil sets the value for Reference to be an explicit nil
func (o *InvoiceMetadata) SetReferenceNil() {
	o.Reference.Set(nil)
}

// UnsetReference ensures that no value is present for Reference, not even an explicit nil
func (o *InvoiceMetadata) UnsetReference() {
	o.Reference.Unset()
}

// GetResellerRef returns the ResellerRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceMetadata) GetResellerRef() string {
	if o == nil || IsNil(o.ResellerRef.Get()) {
		var ret string
		return ret
	}
	return *o.ResellerRef.Get()
}

// GetResellerRefOk returns a tuple with the ResellerRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceMetadata) GetResellerRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResellerRef.Get(), o.ResellerRef.IsSet()
}

// HasResellerRef returns a boolean if a field has been set.
func (o *InvoiceMetadata) HasResellerRef() bool {
	if o != nil && o.ResellerRef.IsSet() {
		return true
	}

	return false
}

// SetResellerRef gets a reference to the given NullableString and assigns it to the ResellerRef field.
func (o *InvoiceMetadata) SetResellerRef(v string) {
	o.ResellerRef.Set(&v)
}

// SetResellerRefNil sets the value for ResellerRef to be an explicit nil
func (o *InvoiceMetadata) SetResellerRefNil() {
	o.ResellerRef.Set(nil)
}

// UnsetResellerRef ensures that no value is present for ResellerRef, not even an explicit nil
func (o *InvoiceMetadata) UnsetResellerRef() {
	o.ResellerRef.Unset()
}

func (o InvoiceMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InvoiceId) {
		toSerialize["invoiceId"] = o.InvoiceId
	}
	if !IsNil(o.ContractId) {
		toSerialize["contractId"] = o.ContractId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.PostingPeriod) {
		toSerialize["postingPeriod"] = o.PostingPeriod
	}
	if !IsNil(o.FinallyPosted) {
		toSerialize["finallyPosted"] = o.FinallyPosted
	}
	if o.Reference.IsSet() {
		toSerialize["reference"] = o.Reference.Get()
	}
	if o.ResellerRef.IsSet() {
		toSerialize["resellerRef"] = o.ResellerRef.Get()
	}
	return toSerialize, nil
}

type NullableInvoiceMetadata struct {
	value *InvoiceMetadata
	isSet bool
}

func (v NullableInvoiceMetadata) Get() *InvoiceMetadata {
	return v.value
}

func (v *NullableInvoiceMetadata) Set(val *InvoiceMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceMetadata(val *InvoiceMetadata) *NullableInvoiceMetadata {
	return &NullableInvoiceMetadata{value: val, isSet: true}
}

func (v NullableInvoiceMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
