/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the Evn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Evn{}

// Evn struct for Evn
type Evn struct {
	Metadata    *EvnMetadata     `json:"metadata,omitempty"`
	Datacenters []EvnDatacenters `json:"datacenters,omitempty"`
	EvnCSV      []string         `json:"evnCSV,omitempty"`
}

// NewEvn instantiates a new Evn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvn() *Evn {
	this := Evn{}

	return &this
}

// NewEvnWithDefaults instantiates a new Evn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvnWithDefaults() *Evn {
	this := Evn{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Evn) GetMetadata() EvnMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret EvnMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Evn) GetMetadataOk() (*EvnMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Evn) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given EvnMetadata and assigns it to the Metadata field.
func (o *Evn) SetMetadata(v EvnMetadata) {
	o.Metadata = &v
}

// GetDatacenters returns the Datacenters field value if set, zero value otherwise.
func (o *Evn) GetDatacenters() []EvnDatacenters {
	if o == nil || IsNil(o.Datacenters) {
		var ret []EvnDatacenters
		return ret
	}
	return o.Datacenters
}

// GetDatacentersOk returns a tuple with the Datacenters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Evn) GetDatacentersOk() ([]EvnDatacenters, bool) {
	if o == nil || IsNil(o.Datacenters) {
		return nil, false
	}
	return o.Datacenters, true
}

// HasDatacenters returns a boolean if a field has been set.
func (o *Evn) HasDatacenters() bool {
	if o != nil && !IsNil(o.Datacenters) {
		return true
	}

	return false
}

// SetDatacenters gets a reference to the given []EvnDatacenters and assigns it to the Datacenters field.
func (o *Evn) SetDatacenters(v []EvnDatacenters) {
	o.Datacenters = v
}

// GetEvnCSV returns the EvnCSV field value if set, zero value otherwise.
func (o *Evn) GetEvnCSV() []string {
	if o == nil || IsNil(o.EvnCSV) {
		var ret []string
		return ret
	}
	return o.EvnCSV
}

// GetEvnCSVOk returns a tuple with the EvnCSV field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Evn) GetEvnCSVOk() ([]string, bool) {
	if o == nil || IsNil(o.EvnCSV) {
		return nil, false
	}
	return o.EvnCSV, true
}

// HasEvnCSV returns a boolean if a field has been set.
func (o *Evn) HasEvnCSV() bool {
	if o != nil && !IsNil(o.EvnCSV) {
		return true
	}

	return false
}

// SetEvnCSV gets a reference to the given []string and assigns it to the EvnCSV field.
func (o *Evn) SetEvnCSV(v []string) {
	o.EvnCSV = v
}

func (o Evn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Evn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Datacenters) {
		toSerialize["datacenters"] = o.Datacenters
	}
	if !IsNil(o.EvnCSV) {
		toSerialize["evnCSV"] = o.EvnCSV
	}
	return toSerialize, nil
}

type NullableEvn struct {
	value *Evn
	isSet bool
}

func (v NullableEvn) Get() *Evn {
	return v.value
}

func (v *NullableEvn) Set(val *Evn) {
	v.value = val
	v.isSet = true
}

func (v NullableEvn) IsSet() bool {
	return v.isSet
}

func (v *NullableEvn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvn(val *Evn) *NullableEvn {
	return &NullableEvn{value: val, isSet: true}
}

func (v NullableEvn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
