/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the ProfilesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfilesGet200Response{}

// ProfilesGet200Response struct for ProfilesGet200Response
type ProfilesGet200Response struct {
	Companies []Metadata `json:"companies,omitempty"`
}

// NewProfilesGet200Response instantiates a new ProfilesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfilesGet200Response() *ProfilesGet200Response {
	this := ProfilesGet200Response{}

	return &this
}

// NewProfilesGet200ResponseWithDefaults instantiates a new ProfilesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfilesGet200ResponseWithDefaults() *ProfilesGet200Response {
	this := ProfilesGet200Response{}
	return &this
}

// GetCompanies returns the Companies field value if set, zero value otherwise.
func (o *ProfilesGet200Response) GetCompanies() []Metadata {
	if o == nil || IsNil(o.Companies) {
		var ret []Metadata
		return ret
	}
	return o.Companies
}

// GetCompaniesOk returns a tuple with the Companies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilesGet200Response) GetCompaniesOk() ([]Metadata, bool) {
	if o == nil || IsNil(o.Companies) {
		return nil, false
	}
	return o.Companies, true
}

// HasCompanies returns a boolean if a field has been set.
func (o *ProfilesGet200Response) HasCompanies() bool {
	if o != nil && !IsNil(o.Companies) {
		return true
	}

	return false
}

// SetCompanies gets a reference to the given []Metadata and assigns it to the Companies field.
func (o *ProfilesGet200Response) SetCompanies(v []Metadata) {
	o.Companies = v
}

func (o ProfilesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfilesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Companies) {
		toSerialize["companies"] = o.Companies
	}
	return toSerialize, nil
}

type NullableProfilesGet200Response struct {
	value *ProfilesGet200Response
	isSet bool
}

func (v NullableProfilesGet200Response) Get() *ProfilesGet200Response {
	return v.value
}

func (v *NullableProfilesGet200Response) Set(val *ProfilesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProfilesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProfilesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfilesGet200Response(val *ProfilesGet200Response) *NullableProfilesGet200Response {
	return &NullableProfilesGet200Response{value: val, isSet: true}
}

func (v NullableProfilesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfilesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
