/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceMeterQuantity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceMeterQuantity{}

// InvoiceMeterQuantity struct for InvoiceMeterQuantity
type InvoiceMeterQuantity struct {
	Quantity *float32 `json:"quantity,omitempty"`
	Unit     *string  `json:"unit,omitempty"`
}

// NewInvoiceMeterQuantity instantiates a new InvoiceMeterQuantity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceMeterQuantity() *InvoiceMeterQuantity {
	this := InvoiceMeterQuantity{}

	return &this
}

// NewInvoiceMeterQuantityWithDefaults instantiates a new InvoiceMeterQuantity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceMeterQuantityWithDefaults() *InvoiceMeterQuantity {
	this := InvoiceMeterQuantity{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InvoiceMeterQuantity) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeterQuantity) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InvoiceMeterQuantity) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *InvoiceMeterQuantity) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *InvoiceMeterQuantity) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeterQuantity) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *InvoiceMeterQuantity) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *InvoiceMeterQuantity) SetUnit(v string) {
	o.Unit = &v
}

func (o InvoiceMeterQuantity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceMeterQuantity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableInvoiceMeterQuantity struct {
	value *InvoiceMeterQuantity
	isSet bool
}

func (v NullableInvoiceMeterQuantity) Get() *InvoiceMeterQuantity {
	return v.value
}

func (v *NullableInvoiceMeterQuantity) Set(val *InvoiceMeterQuantity) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceMeterQuantity) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceMeterQuantity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceMeterQuantity(val *InvoiceMeterQuantity) *NullableInvoiceMeterQuantity {
	return &NullableInvoiceMeterQuantity{value: val, isSet: true}
}

func (v NullableInvoiceMeterQuantity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceMeterQuantity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
