/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the EvnMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvnMetadata{}

// EvnMetadata struct for EvnMetadata
type EvnMetadata struct {
	ContractId *string        `json:"contractId,omitempty"`
	CustomerId *string        `json:"customerId,omitempty"`
	Reference  NullableString `json:"reference,omitempty"`
	Period     *string        `json:"period,omitempty"`
}

// NewEvnMetadata instantiates a new EvnMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvnMetadata() *EvnMetadata {
	this := EvnMetadata{}

	return &this
}

// NewEvnMetadataWithDefaults instantiates a new EvnMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvnMetadataWithDefaults() *EvnMetadata {
	this := EvnMetadata{}
	return &this
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *EvnMetadata) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnMetadata) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *EvnMetadata) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *EvnMetadata) SetContractId(v string) {
	o.ContractId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *EvnMetadata) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnMetadata) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *EvnMetadata) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *EvnMetadata) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetReference returns the Reference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EvnMetadata) GetReference() string {
	if o == nil || IsNil(o.Reference.Get()) {
		var ret string
		return ret
	}
	return *o.Reference.Get()
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EvnMetadata) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reference.Get(), o.Reference.IsSet()
}

// HasReference returns a boolean if a field has been set.
func (o *EvnMetadata) HasReference() bool {
	if o != nil && o.Reference.IsSet() {
		return true
	}

	return false
}

// SetReference gets a reference to the given NullableString and assigns it to the Reference field.
func (o *EvnMetadata) SetReference(v string) {
	o.Reference.Set(&v)
}

// SetReferenceNil sets the value for Reference to be an explicit nil
func (o *EvnMetadata) SetReferenceNil() {
	o.Reference.Set(nil)
}

// UnsetReference ensures that no value is present for Reference, not even an explicit nil
func (o *EvnMetadata) UnsetReference() {
	o.Reference.Unset()
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *EvnMetadata) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnMetadata) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *EvnMetadata) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *EvnMetadata) SetPeriod(v string) {
	o.Period = &v
}

func (o EvnMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvnMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContractId) {
		toSerialize["contractId"] = o.ContractId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if o.Reference.IsSet() {
		toSerialize["reference"] = o.Reference.Get()
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableEvnMetadata struct {
	value *EvnMetadata
	isSet bool
}

func (v NullableEvnMetadata) Get() *EvnMetadata {
	return v.value
}

func (v *NullableEvnMetadata) Set(val *EvnMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEvnMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEvnMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvnMetadata(val *EvnMetadata) *NullableEvnMetadata {
	return &NullableEvnMetadata{value: val, isSet: true}
}

func (v NullableEvnMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvnMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
