/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficTrafficObjNic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficTrafficObjNic{}

// TrafficTrafficObjNic struct for TrafficTrafficObjNic
type TrafficTrafficObjNic struct {
	VdcUUID *string        `json:"vdcUUID,omitempty"`
	VdcName *string        `json:"vdcName,omitempty"`
	Ip      *string        `json:"ip,omitempty"`
	Dates   []TrafficEntry `json:"dates,omitempty"`
}

// NewTrafficTrafficObjNic instantiates a new TrafficTrafficObjNic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficTrafficObjNic() *TrafficTrafficObjNic {
	this := TrafficTrafficObjNic{}

	return &this
}

// NewTrafficTrafficObjNicWithDefaults instantiates a new TrafficTrafficObjNic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficTrafficObjNicWithDefaults() *TrafficTrafficObjNic {
	this := TrafficTrafficObjNic{}
	return &this
}

// GetVdcUUID returns the VdcUUID field value if set, zero value otherwise.
func (o *TrafficTrafficObjNic) GetVdcUUID() string {
	if o == nil || IsNil(o.VdcUUID) {
		var ret string
		return ret
	}
	return *o.VdcUUID
}

// GetVdcUUIDOk returns a tuple with the VdcUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjNic) GetVdcUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.VdcUUID) {
		return nil, false
	}
	return o.VdcUUID, true
}

// HasVdcUUID returns a boolean if a field has been set.
func (o *TrafficTrafficObjNic) HasVdcUUID() bool {
	if o != nil && !IsNil(o.VdcUUID) {
		return true
	}

	return false
}

// SetVdcUUID gets a reference to the given string and assigns it to the VdcUUID field.
func (o *TrafficTrafficObjNic) SetVdcUUID(v string) {
	o.VdcUUID = &v
}

// GetVdcName returns the VdcName field value if set, zero value otherwise.
func (o *TrafficTrafficObjNic) GetVdcName() string {
	if o == nil || IsNil(o.VdcName) {
		var ret string
		return ret
	}
	return *o.VdcName
}

// GetVdcNameOk returns a tuple with the VdcName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjNic) GetVdcNameOk() (*string, bool) {
	if o == nil || IsNil(o.VdcName) {
		return nil, false
	}
	return o.VdcName, true
}

// HasVdcName returns a boolean if a field has been set.
func (o *TrafficTrafficObjNic) HasVdcName() bool {
	if o != nil && !IsNil(o.VdcName) {
		return true
	}

	return false
}

// SetVdcName gets a reference to the given string and assigns it to the VdcName field.
func (o *TrafficTrafficObjNic) SetVdcName(v string) {
	o.VdcName = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *TrafficTrafficObjNic) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjNic) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *TrafficTrafficObjNic) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *TrafficTrafficObjNic) SetIp(v string) {
	o.Ip = &v
}

// GetDates returns the Dates field value if set, zero value otherwise.
func (o *TrafficTrafficObjNic) GetDates() []TrafficEntry {
	if o == nil || IsNil(o.Dates) {
		var ret []TrafficEntry
		return ret
	}
	return o.Dates
}

// GetDatesOk returns a tuple with the Dates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjNic) GetDatesOk() ([]TrafficEntry, bool) {
	if o == nil || IsNil(o.Dates) {
		return nil, false
	}
	return o.Dates, true
}

// HasDates returns a boolean if a field has been set.
func (o *TrafficTrafficObjNic) HasDates() bool {
	if o != nil && !IsNil(o.Dates) {
		return true
	}

	return false
}

// SetDates gets a reference to the given []TrafficEntry and assigns it to the Dates field.
func (o *TrafficTrafficObjNic) SetDates(v []TrafficEntry) {
	o.Dates = v
}

func (o TrafficTrafficObjNic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficTrafficObjNic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VdcUUID) {
		toSerialize["vdcUUID"] = o.VdcUUID
	}
	if !IsNil(o.VdcName) {
		toSerialize["vdcName"] = o.VdcName
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Dates) {
		toSerialize["dates"] = o.Dates
	}
	return toSerialize, nil
}

type NullableTrafficTrafficObjNic struct {
	value *TrafficTrafficObjNic
	isSet bool
}

func (v NullableTrafficTrafficObjNic) Get() *TrafficTrafficObjNic {
	return v.value
}

func (v *NullableTrafficTrafficObjNic) Set(val *TrafficTrafficObjNic) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficTrafficObjNic) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficTrafficObjNic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficTrafficObjNic(val *TrafficTrafficObjNic) *NullableTrafficTrafficObjNic {
	return &NullableTrafficTrafficObjNic{value: val, isSet: true}
}

func (v NullableTrafficTrafficObjNic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficTrafficObjNic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
