/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficTrafficObj type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficTrafficObj{}

// TrafficTrafficObj struct for TrafficTrafficObj
type TrafficTrafficObj struct {
	Vdc []TrafficTrafficObjVdc `json:"vdc,omitempty"`
	Nic []TrafficTrafficObjNic `json:"nic,omitempty"`
}

// NewTrafficTrafficObj instantiates a new TrafficTrafficObj object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficTrafficObj() *TrafficTrafficObj {
	this := TrafficTrafficObj{}

	return &this
}

// NewTrafficTrafficObjWithDefaults instantiates a new TrafficTrafficObj object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficTrafficObjWithDefaults() *TrafficTrafficObj {
	this := TrafficTrafficObj{}
	return &this
}

// GetVdc returns the Vdc field value if set, zero value otherwise.
func (o *TrafficTrafficObj) GetVdc() []TrafficTrafficObjVdc {
	if o == nil || IsNil(o.Vdc) {
		var ret []TrafficTrafficObjVdc
		return ret
	}
	return o.Vdc
}

// GetVdcOk returns a tuple with the Vdc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObj) GetVdcOk() ([]TrafficTrafficObjVdc, bool) {
	if o == nil || IsNil(o.Vdc) {
		return nil, false
	}
	return o.Vdc, true
}

// HasVdc returns a boolean if a field has been set.
func (o *TrafficTrafficObj) HasVdc() bool {
	if o != nil && !IsNil(o.Vdc) {
		return true
	}

	return false
}

// SetVdc gets a reference to the given []TrafficTrafficObjVdc and assigns it to the Vdc field.
func (o *TrafficTrafficObj) SetVdc(v []TrafficTrafficObjVdc) {
	o.Vdc = v
}

// GetNic returns the Nic field value if set, zero value otherwise.
func (o *TrafficTrafficObj) GetNic() []TrafficTrafficObjNic {
	if o == nil || IsNil(o.Nic) {
		var ret []TrafficTrafficObjNic
		return ret
	}
	return o.Nic
}

// GetNicOk returns a tuple with the Nic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObj) GetNicOk() ([]TrafficTrafficObjNic, bool) {
	if o == nil || IsNil(o.Nic) {
		return nil, false
	}
	return o.Nic, true
}

// HasNic returns a boolean if a field has been set.
func (o *TrafficTrafficObj) HasNic() bool {
	if o != nil && !IsNil(o.Nic) {
		return true
	}

	return false
}

// SetNic gets a reference to the given []TrafficTrafficObjNic and assigns it to the Nic field.
func (o *TrafficTrafficObj) SetNic(v []TrafficTrafficObjNic) {
	o.Nic = v
}

func (o TrafficTrafficObj) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficTrafficObj) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vdc) {
		toSerialize["vdc"] = o.Vdc
	}
	if !IsNil(o.Nic) {
		toSerialize["nic"] = o.Nic
	}
	return toSerialize, nil
}

type NullableTrafficTrafficObj struct {
	value *TrafficTrafficObj
	isSet bool
}

func (v NullableTrafficTrafficObj) Get() *TrafficTrafficObj {
	return v.value
}

func (v *NullableTrafficTrafficObj) Set(val *TrafficTrafficObj) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficTrafficObj) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficTrafficObj) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficTrafficObj(val *TrafficTrafficObj) *NullableTrafficTrafficObj {
	return &NullableTrafficTrafficObj{value: val, isSet: true}
}

func (v NullableTrafficTrafficObj) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficTrafficObj) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
