/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the UsageMeter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageMeter{}

// UsageMeter struct for UsageMeter
type UsageMeter struct {
	// Usage meter product code
	MeterId   *string             `json:"meterId,omitempty"`
	MeterDesc *string             `json:"meterDesc,omitempty"`
	Quantity  *UsageMeterQuantity `json:"quantity,omitempty"`
}

// NewUsageMeter instantiates a new UsageMeter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageMeter() *UsageMeter {
	this := UsageMeter{}

	return &this
}

// NewUsageMeterWithDefaults instantiates a new UsageMeter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageMeterWithDefaults() *UsageMeter {
	this := UsageMeter{}
	return &this
}

// GetMeterId returns the MeterId field value if set, zero value otherwise.
func (o *UsageMeter) GetMeterId() string {
	if o == nil || IsNil(o.MeterId) {
		var ret string
		return ret
	}
	return *o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageMeter) GetMeterIdOk() (*string, bool) {
	if o == nil || IsNil(o.MeterId) {
		return nil, false
	}
	return o.MeterId, true
}

// HasMeterId returns a boolean if a field has been set.
func (o *UsageMeter) HasMeterId() bool {
	if o != nil && !IsNil(o.MeterId) {
		return true
	}

	return false
}

// SetMeterId gets a reference to the given string and assigns it to the MeterId field.
func (o *UsageMeter) SetMeterId(v string) {
	o.MeterId = &v
}

// GetMeterDesc returns the MeterDesc field value if set, zero value otherwise.
func (o *UsageMeter) GetMeterDesc() string {
	if o == nil || IsNil(o.MeterDesc) {
		var ret string
		return ret
	}
	return *o.MeterDesc
}

// GetMeterDescOk returns a tuple with the MeterDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageMeter) GetMeterDescOk() (*string, bool) {
	if o == nil || IsNil(o.MeterDesc) {
		return nil, false
	}
	return o.MeterDesc, true
}

// HasMeterDesc returns a boolean if a field has been set.
func (o *UsageMeter) HasMeterDesc() bool {
	if o != nil && !IsNil(o.MeterDesc) {
		return true
	}

	return false
}

// SetMeterDesc gets a reference to the given string and assigns it to the MeterDesc field.
func (o *UsageMeter) SetMeterDesc(v string) {
	o.MeterDesc = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *UsageMeter) GetQuantity() UsageMeterQuantity {
	if o == nil || IsNil(o.Quantity) {
		var ret UsageMeterQuantity
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageMeter) GetQuantityOk() (*UsageMeterQuantity, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *UsageMeter) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given UsageMeterQuantity and assigns it to the Quantity field.
func (o *UsageMeter) SetQuantity(v UsageMeterQuantity) {
	o.Quantity = &v
}

func (o UsageMeter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageMeter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MeterId) {
		toSerialize["meterId"] = o.MeterId
	}
	if !IsNil(o.MeterDesc) {
		toSerialize["meterDesc"] = o.MeterDesc
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableUsageMeter struct {
	value *UsageMeter
	isSet bool
}

func (v NullableUsageMeter) Get() *UsageMeter {
	return v.value
}

func (v *NullableUsageMeter) Set(val *UsageMeter) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageMeter) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageMeter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageMeter(val *UsageMeter) *NullableUsageMeter {
	return &NullableUsageMeter{value: val, isSet: true}
}

func (v NullableUsageMeter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageMeter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
