/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the ProductsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsGet200Response{}

// ProductsGet200Response struct for ProductsGet200Response
type ProductsGet200Response struct {
	Metadata  *Metadata `json:"metadata,omitempty"`
	Liability *string   `json:"liability,omitempty"`
	Products  []Product `json:"products,omitempty"`
}

// NewProductsGet200Response instantiates a new ProductsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsGet200Response() *ProductsGet200Response {
	this := ProductsGet200Response{}

	return &this
}

// NewProductsGet200ResponseWithDefaults instantiates a new ProductsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsGet200ResponseWithDefaults() *ProductsGet200Response {
	this := ProductsGet200Response{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ProductsGet200Response) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsGet200Response) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ProductsGet200Response) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *ProductsGet200Response) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetLiability returns the Liability field value if set, zero value otherwise.
func (o *ProductsGet200Response) GetLiability() string {
	if o == nil || IsNil(o.Liability) {
		var ret string
		return ret
	}
	return *o.Liability
}

// GetLiabilityOk returns a tuple with the Liability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsGet200Response) GetLiabilityOk() (*string, bool) {
	if o == nil || IsNil(o.Liability) {
		return nil, false
	}
	return o.Liability, true
}

// HasLiability returns a boolean if a field has been set.
func (o *ProductsGet200Response) HasLiability() bool {
	if o != nil && !IsNil(o.Liability) {
		return true
	}

	return false
}

// SetLiability gets a reference to the given string and assigns it to the Liability field.
func (o *ProductsGet200Response) SetLiability(v string) {
	o.Liability = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *ProductsGet200Response) GetProducts() []Product {
	if o == nil || IsNil(o.Products) {
		var ret []Product
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsGet200Response) GetProductsOk() ([]Product, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *ProductsGet200Response) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []Product and assigns it to the Products field.
func (o *ProductsGet200Response) SetProducts(v []Product) {
	o.Products = v
}

func (o ProductsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Liability) {
		toSerialize["liability"] = o.Liability
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	return toSerialize, nil
}

type NullableProductsGet200Response struct {
	value *ProductsGet200Response
	isSet bool
}

func (v NullableProductsGet200Response) Get() *ProductsGet200Response {
	return v.value
}

func (v *NullableProductsGet200Response) Set(val *ProductsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsGet200Response(val *ProductsGet200Response) *NullableProductsGet200Response {
	return &NullableProductsGet200Response{value: val, isSet: true}
}

func (v NullableProductsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
