/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the EvnDatacenters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvnDatacenters{}

// EvnDatacenters struct for EvnDatacenters
type EvnDatacenters struct {
	VdcUUID *string   `json:"vdcUUID,omitempty"`
	Name    *string   `json:"name,omitempty"`
	Data    []EvnItem `json:"data,omitempty"`
}

// NewEvnDatacenters instantiates a new EvnDatacenters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvnDatacenters() *EvnDatacenters {
	this := EvnDatacenters{}

	return &this
}

// NewEvnDatacentersWithDefaults instantiates a new EvnDatacenters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvnDatacentersWithDefaults() *EvnDatacenters {
	this := EvnDatacenters{}
	return &this
}

// GetVdcUUID returns the VdcUUID field value if set, zero value otherwise.
func (o *EvnDatacenters) GetVdcUUID() string {
	if o == nil || IsNil(o.VdcUUID) {
		var ret string
		return ret
	}
	return *o.VdcUUID
}

// GetVdcUUIDOk returns a tuple with the VdcUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnDatacenters) GetVdcUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.VdcUUID) {
		return nil, false
	}
	return o.VdcUUID, true
}

// HasVdcUUID returns a boolean if a field has been set.
func (o *EvnDatacenters) HasVdcUUID() bool {
	if o != nil && !IsNil(o.VdcUUID) {
		return true
	}

	return false
}

// SetVdcUUID gets a reference to the given string and assigns it to the VdcUUID field.
func (o *EvnDatacenters) SetVdcUUID(v string) {
	o.VdcUUID = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EvnDatacenters) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnDatacenters) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EvnDatacenters) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EvnDatacenters) SetName(v string) {
	o.Name = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EvnDatacenters) GetData() []EvnItem {
	if o == nil || IsNil(o.Data) {
		var ret []EvnItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnDatacenters) GetDataOk() ([]EvnItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EvnDatacenters) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []EvnItem and assigns it to the Data field.
func (o *EvnDatacenters) SetData(v []EvnItem) {
	o.Data = v
}

func (o EvnDatacenters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvnDatacenters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VdcUUID) {
		toSerialize["vdcUUID"] = o.VdcUUID
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEvnDatacenters struct {
	value *EvnDatacenters
	isSet bool
}

func (v NullableEvnDatacenters) Get() *EvnDatacenters {
	return v.value
}

func (v *NullableEvnDatacenters) Set(val *EvnDatacenters) {
	v.value = val
	v.isSet = true
}

func (v NullableEvnDatacenters) IsSet() bool {
	return v.isSet
}

func (v *NullableEvnDatacenters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvnDatacenters(val *EvnDatacenters) *NullableEvnDatacenters {
	return &NullableEvnDatacenters{value: val, isSet: true}
}

func (v NullableEvnDatacenters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvnDatacenters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
