/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceDatacenters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceDatacenters{}

// InvoiceDatacenters struct for InvoiceDatacenters
type InvoiceDatacenters struct {
	Id       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Location *string `json:"location,omitempty"`
	// Product group of the data center
	ProductGroup NullableString            `json:"productGroup,omitempty"`
	Meters       []InvoiceMeter            `json:"meters,omitempty"`
	Rebate       *InvoiceDatacentersRebate `json:"rebate,omitempty"`
}

// NewInvoiceDatacenters instantiates a new InvoiceDatacenters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceDatacenters() *InvoiceDatacenters {
	this := InvoiceDatacenters{}

	return &this
}

// NewInvoiceDatacentersWithDefaults instantiates a new InvoiceDatacenters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceDatacentersWithDefaults() *InvoiceDatacenters {
	this := InvoiceDatacenters{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InvoiceDatacenters) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacenters) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InvoiceDatacenters) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InvoiceDatacenters) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacenters) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InvoiceDatacenters) SetName(v string) {
	o.Name = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *InvoiceDatacenters) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacenters) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *InvoiceDatacenters) SetLocation(v string) {
	o.Location = &v
}

// GetProductGroup returns the ProductGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceDatacenters) GetProductGroup() string {
	if o == nil || IsNil(o.ProductGroup.Get()) {
		var ret string
		return ret
	}
	return *o.ProductGroup.Get()
}

// GetProductGroupOk returns a tuple with the ProductGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceDatacenters) GetProductGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductGroup.Get(), o.ProductGroup.IsSet()
}

// HasProductGroup returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasProductGroup() bool {
	if o != nil && o.ProductGroup.IsSet() {
		return true
	}

	return false
}

// SetProductGroup gets a reference to the given NullableString and assigns it to the ProductGroup field.
func (o *InvoiceDatacenters) SetProductGroup(v string) {
	o.ProductGroup.Set(&v)
}

// SetProductGroupNil sets the value for ProductGroup to be an explicit nil
func (o *InvoiceDatacenters) SetProductGroupNil() {
	o.ProductGroup.Set(nil)
}

// UnsetProductGroup ensures that no value is present for ProductGroup, not even an explicit nil
func (o *InvoiceDatacenters) UnsetProductGroup() {
	o.ProductGroup.Unset()
}

// GetMeters returns the Meters field value if set, zero value otherwise.
func (o *InvoiceDatacenters) GetMeters() []InvoiceMeter {
	if o == nil || IsNil(o.Meters) {
		var ret []InvoiceMeter
		return ret
	}
	return o.Meters
}

// GetMetersOk returns a tuple with the Meters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacenters) GetMetersOk() ([]InvoiceMeter, bool) {
	if o == nil || IsNil(o.Meters) {
		return nil, false
	}
	return o.Meters, true
}

// HasMeters returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasMeters() bool {
	if o != nil && !IsNil(o.Meters) {
		return true
	}

	return false
}

// SetMeters gets a reference to the given []InvoiceMeter and assigns it to the Meters field.
func (o *InvoiceDatacenters) SetMeters(v []InvoiceMeter) {
	o.Meters = v
}

// GetRebate returns the Rebate field value if set, zero value otherwise.
func (o *InvoiceDatacenters) GetRebate() InvoiceDatacentersRebate {
	if o == nil || IsNil(o.Rebate) {
		var ret InvoiceDatacentersRebate
		return ret
	}
	return *o.Rebate
}

// GetRebateOk returns a tuple with the Rebate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceDatacenters) GetRebateOk() (*InvoiceDatacentersRebate, bool) {
	if o == nil || IsNil(o.Rebate) {
		return nil, false
	}
	return o.Rebate, true
}

// HasRebate returns a boolean if a field has been set.
func (o *InvoiceDatacenters) HasRebate() bool {
	if o != nil && !IsNil(o.Rebate) {
		return true
	}

	return false
}

// SetRebate gets a reference to the given InvoiceDatacentersRebate and assigns it to the Rebate field.
func (o *InvoiceDatacenters) SetRebate(v InvoiceDatacentersRebate) {
	o.Rebate = &v
}

func (o InvoiceDatacenters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceDatacenters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if o.ProductGroup.IsSet() {
		toSerialize["productGroup"] = o.ProductGroup.Get()
	}
	if !IsNil(o.Meters) {
		toSerialize["meters"] = o.Meters
	}
	if !IsNil(o.Rebate) {
		toSerialize["rebate"] = o.Rebate
	}
	return toSerialize, nil
}

type NullableInvoiceDatacenters struct {
	value *InvoiceDatacenters
	isSet bool
}

func (v NullableInvoiceDatacenters) Get() *InvoiceDatacenters {
	return v.value
}

func (v *NullableInvoiceDatacenters) Set(val *InvoiceDatacenters) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceDatacenters) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceDatacenters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceDatacenters(val *InvoiceDatacenters) *NullableInvoiceDatacenters {
	return &NullableInvoiceDatacenters{value: val, isSet: true}
}

func (v NullableInvoiceDatacenters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceDatacenters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
