/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the UsageDataCenter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageDataCenter{}

// UsageDataCenter struct for UsageDataCenter
type UsageDataCenter struct {
	Id       *string      `json:"id,omitempty"`
	Name     *string      `json:"name,omitempty"`
	Location *string      `json:"location,omitempty"`
	Meters   []UsageMeter `json:"meters,omitempty"`
}

// NewUsageDataCenter instantiates a new UsageDataCenter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageDataCenter() *UsageDataCenter {
	this := UsageDataCenter{}

	return &this
}

// NewUsageDataCenterWithDefaults instantiates a new UsageDataCenter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageDataCenterWithDefaults() *UsageDataCenter {
	this := UsageDataCenter{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UsageDataCenter) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDataCenter) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UsageDataCenter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UsageDataCenter) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UsageDataCenter) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDataCenter) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UsageDataCenter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UsageDataCenter) SetName(v string) {
	o.Name = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *UsageDataCenter) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDataCenter) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *UsageDataCenter) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *UsageDataCenter) SetLocation(v string) {
	o.Location = &v
}

// GetMeters returns the Meters field value if set, zero value otherwise.
func (o *UsageDataCenter) GetMeters() []UsageMeter {
	if o == nil || IsNil(o.Meters) {
		var ret []UsageMeter
		return ret
	}
	return o.Meters
}

// GetMetersOk returns a tuple with the Meters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageDataCenter) GetMetersOk() ([]UsageMeter, bool) {
	if o == nil || IsNil(o.Meters) {
		return nil, false
	}
	return o.Meters, true
}

// HasMeters returns a boolean if a field has been set.
func (o *UsageDataCenter) HasMeters() bool {
	if o != nil && !IsNil(o.Meters) {
		return true
	}

	return false
}

// SetMeters gets a reference to the given []UsageMeter and assigns it to the Meters field.
func (o *UsageDataCenter) SetMeters(v []UsageMeter) {
	o.Meters = v
}

func (o UsageDataCenter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageDataCenter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Meters) {
		toSerialize["meters"] = o.Meters
	}
	return toSerialize, nil
}

type NullableUsageDataCenter struct {
	value *UsageDataCenter
	isSet bool
}

func (v NullableUsageDataCenter) Get() *UsageDataCenter {
	return v.value
}

func (v *NullableUsageDataCenter) Set(val *UsageDataCenter) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageDataCenter) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageDataCenter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageDataCenter(val *UsageDataCenter) *NullableUsageDataCenter {
	return &NullableUsageDataCenter{value: val, isSet: true}
}

func (v NullableUsageDataCenter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageDataCenter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
