/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficTrafficObjVdc type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficTrafficObjVdc{}

// TrafficTrafficObjVdc struct for TrafficTrafficObjVdc
type TrafficTrafficObjVdc struct {
	VdcUUID *string        `json:"vdcUUID,omitempty"`
	VdcName *string        `json:"vdcName,omitempty"`
	Dates   []TrafficEntry `json:"dates,omitempty"`
}

// NewTrafficTrafficObjVdc instantiates a new TrafficTrafficObjVdc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficTrafficObjVdc() *TrafficTrafficObjVdc {
	this := TrafficTrafficObjVdc{}

	return &this
}

// NewTrafficTrafficObjVdcWithDefaults instantiates a new TrafficTrafficObjVdc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficTrafficObjVdcWithDefaults() *TrafficTrafficObjVdc {
	this := TrafficTrafficObjVdc{}
	return &this
}

// GetVdcUUID returns the VdcUUID field value if set, zero value otherwise.
func (o *TrafficTrafficObjVdc) GetVdcUUID() string {
	if o == nil || IsNil(o.VdcUUID) {
		var ret string
		return ret
	}
	return *o.VdcUUID
}

// GetVdcUUIDOk returns a tuple with the VdcUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjVdc) GetVdcUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.VdcUUID) {
		return nil, false
	}
	return o.VdcUUID, true
}

// HasVdcUUID returns a boolean if a field has been set.
func (o *TrafficTrafficObjVdc) HasVdcUUID() bool {
	if o != nil && !IsNil(o.VdcUUID) {
		return true
	}

	return false
}

// SetVdcUUID gets a reference to the given string and assigns it to the VdcUUID field.
func (o *TrafficTrafficObjVdc) SetVdcUUID(v string) {
	o.VdcUUID = &v
}

// GetVdcName returns the VdcName field value if set, zero value otherwise.
func (o *TrafficTrafficObjVdc) GetVdcName() string {
	if o == nil || IsNil(o.VdcName) {
		var ret string
		return ret
	}
	return *o.VdcName
}

// GetVdcNameOk returns a tuple with the VdcName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjVdc) GetVdcNameOk() (*string, bool) {
	if o == nil || IsNil(o.VdcName) {
		return nil, false
	}
	return o.VdcName, true
}

// HasVdcName returns a boolean if a field has been set.
func (o *TrafficTrafficObjVdc) HasVdcName() bool {
	if o != nil && !IsNil(o.VdcName) {
		return true
	}

	return false
}

// SetVdcName gets a reference to the given string and assigns it to the VdcName field.
func (o *TrafficTrafficObjVdc) SetVdcName(v string) {
	o.VdcName = &v
}

// GetDates returns the Dates field value if set, zero value otherwise.
func (o *TrafficTrafficObjVdc) GetDates() []TrafficEntry {
	if o == nil || IsNil(o.Dates) {
		var ret []TrafficEntry
		return ret
	}
	return o.Dates
}

// GetDatesOk returns a tuple with the Dates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficTrafficObjVdc) GetDatesOk() ([]TrafficEntry, bool) {
	if o == nil || IsNil(o.Dates) {
		return nil, false
	}
	return o.Dates, true
}

// HasDates returns a boolean if a field has been set.
func (o *TrafficTrafficObjVdc) HasDates() bool {
	if o != nil && !IsNil(o.Dates) {
		return true
	}

	return false
}

// SetDates gets a reference to the given []TrafficEntry and assigns it to the Dates field.
func (o *TrafficTrafficObjVdc) SetDates(v []TrafficEntry) {
	o.Dates = v
}

func (o TrafficTrafficObjVdc) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficTrafficObjVdc) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VdcUUID) {
		toSerialize["vdcUUID"] = o.VdcUUID
	}
	if !IsNil(o.VdcName) {
		toSerialize["vdcName"] = o.VdcName
	}
	if !IsNil(o.Dates) {
		toSerialize["dates"] = o.Dates
	}
	return toSerialize, nil
}

type NullableTrafficTrafficObjVdc struct {
	value *TrafficTrafficObjVdc
	isSet bool
}

func (v NullableTrafficTrafficObjVdc) Get() *TrafficTrafficObjVdc {
	return v.value
}

func (v *NullableTrafficTrafficObjVdc) Set(val *TrafficTrafficObjVdc) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficTrafficObjVdc) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficTrafficObjVdc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficTrafficObjVdc(val *TrafficTrafficObjVdc) *NullableTrafficTrafficObjVdc {
	return &NullableTrafficTrafficObjVdc{value: val, isSet: true}
}

func (v NullableTrafficTrafficObjVdc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficTrafficObjVdc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
