/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceMeter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceMeter{}

// InvoiceMeter struct for InvoiceMeter
type InvoiceMeter struct {
	MeterId   *string `json:"meterId,omitempty"`
	MeterDesc *string `json:"meterDesc,omitempty"`
	// Product group of the price item
	ProductGroup NullableString        `json:"productGroup,omitempty"`
	Quantity     *InvoiceMeterQuantity `json:"quantity,omitempty"`
	Rate         *InvoiceTotal         `json:"rate,omitempty"`
	Amount       *InvoiceTotal         `json:"amount,omitempty"`
}

// NewInvoiceMeter instantiates a new InvoiceMeter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceMeter() *InvoiceMeter {
	this := InvoiceMeter{}

	return &this
}

// NewInvoiceMeterWithDefaults instantiates a new InvoiceMeter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceMeterWithDefaults() *InvoiceMeter {
	this := InvoiceMeter{}
	return &this
}

// GetMeterId returns the MeterId field value if set, zero value otherwise.
func (o *InvoiceMeter) GetMeterId() string {
	if o == nil || IsNil(o.MeterId) {
		var ret string
		return ret
	}
	return *o.MeterId
}

// GetMeterIdOk returns a tuple with the MeterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeter) GetMeterIdOk() (*string, bool) {
	if o == nil || IsNil(o.MeterId) {
		return nil, false
	}
	return o.MeterId, true
}

// HasMeterId returns a boolean if a field has been set.
func (o *InvoiceMeter) HasMeterId() bool {
	if o != nil && !IsNil(o.MeterId) {
		return true
	}

	return false
}

// SetMeterId gets a reference to the given string and assigns it to the MeterId field.
func (o *InvoiceMeter) SetMeterId(v string) {
	o.MeterId = &v
}

// GetMeterDesc returns the MeterDesc field value if set, zero value otherwise.
func (o *InvoiceMeter) GetMeterDesc() string {
	if o == nil || IsNil(o.MeterDesc) {
		var ret string
		return ret
	}
	return *o.MeterDesc
}

// GetMeterDescOk returns a tuple with the MeterDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeter) GetMeterDescOk() (*string, bool) {
	if o == nil || IsNil(o.MeterDesc) {
		return nil, false
	}
	return o.MeterDesc, true
}

// HasMeterDesc returns a boolean if a field has been set.
func (o *InvoiceMeter) HasMeterDesc() bool {
	if o != nil && !IsNil(o.MeterDesc) {
		return true
	}

	return false
}

// SetMeterDesc gets a reference to the given string and assigns it to the MeterDesc field.
func (o *InvoiceMeter) SetMeterDesc(v string) {
	o.MeterDesc = &v
}

// GetProductGroup returns the ProductGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceMeter) GetProductGroup() string {
	if o == nil || IsNil(o.ProductGroup.Get()) {
		var ret string
		return ret
	}
	return *o.ProductGroup.Get()
}

// GetProductGroupOk returns a tuple with the ProductGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceMeter) GetProductGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductGroup.Get(), o.ProductGroup.IsSet()
}

// HasProductGroup returns a boolean if a field has been set.
func (o *InvoiceMeter) HasProductGroup() bool {
	if o != nil && o.ProductGroup.IsSet() {
		return true
	}

	return false
}

// SetProductGroup gets a reference to the given NullableString and assigns it to the ProductGroup field.
func (o *InvoiceMeter) SetProductGroup(v string) {
	o.ProductGroup.Set(&v)
}

// SetProductGroupNil sets the value for ProductGroup to be an explicit nil
func (o *InvoiceMeter) SetProductGroupNil() {
	o.ProductGroup.Set(nil)
}

// UnsetProductGroup ensures that no value is present for ProductGroup, not even an explicit nil
func (o *InvoiceMeter) UnsetProductGroup() {
	o.ProductGroup.Unset()
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InvoiceMeter) GetQuantity() InvoiceMeterQuantity {
	if o == nil || IsNil(o.Quantity) {
		var ret InvoiceMeterQuantity
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeter) GetQuantityOk() (*InvoiceMeterQuantity, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InvoiceMeter) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given InvoiceMeterQuantity and assigns it to the Quantity field.
func (o *InvoiceMeter) SetQuantity(v InvoiceMeterQuantity) {
	o.Quantity = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *InvoiceMeter) GetRate() InvoiceTotal {
	if o == nil || IsNil(o.Rate) {
		var ret InvoiceTotal
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeter) GetRateOk() (*InvoiceTotal, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *InvoiceMeter) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given InvoiceTotal and assigns it to the Rate field.
func (o *InvoiceMeter) SetRate(v InvoiceTotal) {
	o.Rate = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *InvoiceMeter) GetAmount() InvoiceTotal {
	if o == nil || IsNil(o.Amount) {
		var ret InvoiceTotal
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceMeter) GetAmountOk() (*InvoiceTotal, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *InvoiceMeter) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given InvoiceTotal and assigns it to the Amount field.
func (o *InvoiceMeter) SetAmount(v InvoiceTotal) {
	o.Amount = &v
}

func (o InvoiceMeter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceMeter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MeterId) {
		toSerialize["meterId"] = o.MeterId
	}
	if !IsNil(o.MeterDesc) {
		toSerialize["meterDesc"] = o.MeterDesc
	}
	if o.ProductGroup.IsSet() {
		toSerialize["productGroup"] = o.ProductGroup.Get()
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableInvoiceMeter struct {
	value *InvoiceMeter
	isSet bool
}

func (v NullableInvoiceMeter) Get() *InvoiceMeter {
	return v.value
}

func (v *NullableInvoiceMeter) Set(val *InvoiceMeter) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceMeter) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceMeter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceMeter(val *InvoiceMeter) *NullableInvoiceMeter {
	return &NullableInvoiceMeter{value: val, isSet: true}
}

func (v NullableInvoiceMeter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceMeter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
