/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the InvoiceTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceTotal{}

// InvoiceTotal struct for InvoiceTotal
type InvoiceTotal struct {
	Quantity *float32 `json:"quantity,omitempty"`
	Unit     *string  `json:"unit,omitempty"`
}

// NewInvoiceTotal instantiates a new InvoiceTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceTotal() *InvoiceTotal {
	this := InvoiceTotal{}

	return &this
}

// NewInvoiceTotalWithDefaults instantiates a new InvoiceTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceTotalWithDefaults() *InvoiceTotal {
	this := InvoiceTotal{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InvoiceTotal) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceTotal) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InvoiceTotal) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *InvoiceTotal) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *InvoiceTotal) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceTotal) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *InvoiceTotal) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *InvoiceTotal) SetUnit(v string) {
	o.Unit = &v
}

func (o InvoiceTotal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableInvoiceTotal struct {
	value *InvoiceTotal
	isSet bool
}

func (v NullableInvoiceTotal) Get() *InvoiceTotal {
	return v.value
}

func (v *NullableInvoiceTotal) Set(val *InvoiceTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceTotal(val *InvoiceTotal) *NullableInvoiceTotal {
	return &NullableInvoiceTotal{value: val, isSet: true}
}

func (v NullableInvoiceTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
