/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"

	"time"
)

// checks if the EvnItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EvnItem{}

// EvnItem struct for EvnItem
type EvnItem struct {
	ResourceType         *string    `json:"resourceType,omitempty"`
	ResourceUUID         *string    `json:"resourceUUID,omitempty"`
	IntervalMin          *int32     `json:"intervalMin,omitempty"`
	IntervalDivisor      *int32     `json:"intervalDivisor,omitempty"`
	From                 *IonosTime `json:"from,omitempty"`
	To                   *IonosTime `json:"to,omitempty"`
	ItemStub             *string    `json:"itemStub,omitempty"`
	Value                *float32   `json:"value,omitempty"`
	ValueDivisor         *int32     `json:"valueDivisor,omitempty"`
	AdditionalParameters *string    `json:"additionalParameters,omitempty"`
}

// NewEvnItem instantiates a new EvnItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvnItem() *EvnItem {
	this := EvnItem{}

	return &this
}

// NewEvnItemWithDefaults instantiates a new EvnItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEvnItemWithDefaults() *EvnItem {
	this := EvnItem{}
	return &this
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *EvnItem) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *EvnItem) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *EvnItem) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetResourceUUID returns the ResourceUUID field value if set, zero value otherwise.
func (o *EvnItem) GetResourceUUID() string {
	if o == nil || IsNil(o.ResourceUUID) {
		var ret string
		return ret
	}
	return *o.ResourceUUID
}

// GetResourceUUIDOk returns a tuple with the ResourceUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetResourceUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceUUID) {
		return nil, false
	}
	return o.ResourceUUID, true
}

// HasResourceUUID returns a boolean if a field has been set.
func (o *EvnItem) HasResourceUUID() bool {
	if o != nil && !IsNil(o.ResourceUUID) {
		return true
	}

	return false
}

// SetResourceUUID gets a reference to the given string and assigns it to the ResourceUUID field.
func (o *EvnItem) SetResourceUUID(v string) {
	o.ResourceUUID = &v
}

// GetIntervalMin returns the IntervalMin field value if set, zero value otherwise.
func (o *EvnItem) GetIntervalMin() int32 {
	if o == nil || IsNil(o.IntervalMin) {
		var ret int32
		return ret
	}
	return *o.IntervalMin
}

// GetIntervalMinOk returns a tuple with the IntervalMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetIntervalMinOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalMin) {
		return nil, false
	}
	return o.IntervalMin, true
}

// HasIntervalMin returns a boolean if a field has been set.
func (o *EvnItem) HasIntervalMin() bool {
	if o != nil && !IsNil(o.IntervalMin) {
		return true
	}

	return false
}

// SetIntervalMin gets a reference to the given int32 and assigns it to the IntervalMin field.
func (o *EvnItem) SetIntervalMin(v int32) {
	o.IntervalMin = &v
}

// GetIntervalDivisor returns the IntervalDivisor field value if set, zero value otherwise.
func (o *EvnItem) GetIntervalDivisor() int32 {
	if o == nil || IsNil(o.IntervalDivisor) {
		var ret int32
		return ret
	}
	return *o.IntervalDivisor
}

// GetIntervalDivisorOk returns a tuple with the IntervalDivisor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetIntervalDivisorOk() (*int32, bool) {
	if o == nil || IsNil(o.IntervalDivisor) {
		return nil, false
	}
	return o.IntervalDivisor, true
}

// HasIntervalDivisor returns a boolean if a field has been set.
func (o *EvnItem) HasIntervalDivisor() bool {
	if o != nil && !IsNil(o.IntervalDivisor) {
		return true
	}

	return false
}

// SetIntervalDivisor gets a reference to the given int32 and assigns it to the IntervalDivisor field.
func (o *EvnItem) SetIntervalDivisor(v int32) {
	o.IntervalDivisor = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *EvnItem) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return o.From.Time
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return &o.From.Time, true
}

// HasFrom returns a boolean if a field has been set.
func (o *EvnItem) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *EvnItem) SetFrom(v time.Time) {
	o.From = &IonosTime{v}
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *EvnItem) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return o.To.Time
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return &o.To.Time, true
}

// HasTo returns a boolean if a field has been set.
func (o *EvnItem) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *EvnItem) SetTo(v time.Time) {
	o.To = &IonosTime{v}
}

// GetItemStub returns the ItemStub field value if set, zero value otherwise.
func (o *EvnItem) GetItemStub() string {
	if o == nil || IsNil(o.ItemStub) {
		var ret string
		return ret
	}
	return *o.ItemStub
}

// GetItemStubOk returns a tuple with the ItemStub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetItemStubOk() (*string, bool) {
	if o == nil || IsNil(o.ItemStub) {
		return nil, false
	}
	return o.ItemStub, true
}

// HasItemStub returns a boolean if a field has been set.
func (o *EvnItem) HasItemStub() bool {
	if o != nil && !IsNil(o.ItemStub) {
		return true
	}

	return false
}

// SetItemStub gets a reference to the given string and assigns it to the ItemStub field.
func (o *EvnItem) SetItemStub(v string) {
	o.ItemStub = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *EvnItem) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *EvnItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *EvnItem) SetValue(v float32) {
	o.Value = &v
}

// GetValueDivisor returns the ValueDivisor field value if set, zero value otherwise.
func (o *EvnItem) GetValueDivisor() int32 {
	if o == nil || IsNil(o.ValueDivisor) {
		var ret int32
		return ret
	}
	return *o.ValueDivisor
}

// GetValueDivisorOk returns a tuple with the ValueDivisor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetValueDivisorOk() (*int32, bool) {
	if o == nil || IsNil(o.ValueDivisor) {
		return nil, false
	}
	return o.ValueDivisor, true
}

// HasValueDivisor returns a boolean if a field has been set.
func (o *EvnItem) HasValueDivisor() bool {
	if o != nil && !IsNil(o.ValueDivisor) {
		return true
	}

	return false
}

// SetValueDivisor gets a reference to the given int32 and assigns it to the ValueDivisor field.
func (o *EvnItem) SetValueDivisor(v int32) {
	o.ValueDivisor = &v
}

// GetAdditionalParameters returns the AdditionalParameters field value if set, zero value otherwise.
func (o *EvnItem) GetAdditionalParameters() string {
	if o == nil || IsNil(o.AdditionalParameters) {
		var ret string
		return ret
	}
	return *o.AdditionalParameters
}

// GetAdditionalParametersOk returns a tuple with the AdditionalParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EvnItem) GetAdditionalParametersOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalParameters) {
		return nil, false
	}
	return o.AdditionalParameters, true
}

// HasAdditionalParameters returns a boolean if a field has been set.
func (o *EvnItem) HasAdditionalParameters() bool {
	if o != nil && !IsNil(o.AdditionalParameters) {
		return true
	}

	return false
}

// SetAdditionalParameters gets a reference to the given string and assigns it to the AdditionalParameters field.
func (o *EvnItem) SetAdditionalParameters(v string) {
	o.AdditionalParameters = &v
}

func (o EvnItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EvnItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	if !IsNil(o.ResourceUUID) {
		toSerialize["resourceUUID"] = o.ResourceUUID
	}
	if !IsNil(o.IntervalMin) {
		toSerialize["intervalMin"] = o.IntervalMin
	}
	if !IsNil(o.IntervalDivisor) {
		toSerialize["intervalDivisor"] = o.IntervalDivisor
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.ItemStub) {
		toSerialize["itemStub"] = o.ItemStub
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.ValueDivisor) {
		toSerialize["valueDivisor"] = o.ValueDivisor
	}
	if !IsNil(o.AdditionalParameters) {
		toSerialize["additionalParameters"] = o.AdditionalParameters
	}
	return toSerialize, nil
}

type NullableEvnItem struct {
	value *EvnItem
	isSet bool
}

func (v NullableEvnItem) Get() *EvnItem {
	return v.value
}

func (v *NullableEvnItem) Set(val *EvnItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEvnItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEvnItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvnItem(val *EvnItem) *NullableEvnItem {
	return &NullableEvnItem{value: val, isSet: true}
}

func (v NullableEvnItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvnItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
