/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the TrafficEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficEntry{}

// TrafficEntry struct for TrafficEntry
type TrafficEntry struct {
	Date *string  `json:"Date,omitempty"`
	In   *float32 `json:"In,omitempty"`
	Out  *float32 `json:"Out,omitempty"`
}

// NewTrafficEntry instantiates a new TrafficEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficEntry() *TrafficEntry {
	this := TrafficEntry{}

	return &this
}

// NewTrafficEntryWithDefaults instantiates a new TrafficEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficEntryWithDefaults() *TrafficEntry {
	this := TrafficEntry{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *TrafficEntry) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficEntry) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *TrafficEntry) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *TrafficEntry) SetDate(v string) {
	o.Date = &v
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *TrafficEntry) GetIn() float32 {
	if o == nil || IsNil(o.In) {
		var ret float32
		return ret
	}
	return *o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficEntry) GetInOk() (*float32, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *TrafficEntry) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given float32 and assigns it to the In field.
func (o *TrafficEntry) SetIn(v float32) {
	o.In = &v
}

// GetOut returns the Out field value if set, zero value otherwise.
func (o *TrafficEntry) GetOut() float32 {
	if o == nil || IsNil(o.Out) {
		var ret float32
		return ret
	}
	return *o.Out
}

// GetOutOk returns a tuple with the Out field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficEntry) GetOutOk() (*float32, bool) {
	if o == nil || IsNil(o.Out) {
		return nil, false
	}
	return o.Out, true
}

// HasOut returns a boolean if a field has been set.
func (o *TrafficEntry) HasOut() bool {
	if o != nil && !IsNil(o.Out) {
		return true
	}

	return false
}

// SetOut gets a reference to the given float32 and assigns it to the Out field.
func (o *TrafficEntry) SetOut(v float32) {
	o.Out = &v
}

func (o TrafficEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["Date"] = o.Date
	}
	if !IsNil(o.In) {
		toSerialize["In"] = o.In
	}
	if !IsNil(o.Out) {
		toSerialize["Out"] = o.Out
	}
	return toSerialize, nil
}

type NullableTrafficEntry struct {
	value *TrafficEntry
	isSet bool
}

func (v NullableTrafficEntry) Get() *TrafficEntry {
	return v.value
}

func (v *NullableTrafficEntry) Set(val *TrafficEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficEntry(val *TrafficEntry) *NullableTrafficEntry {
	return &NullableTrafficEntry{value: val, isSet: true}
}

func (v NullableTrafficEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
