/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the UtilizationDataCenter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UtilizationDataCenter{}

// UtilizationDataCenter struct for UtilizationDataCenter
type UtilizationDataCenter struct {
	Id     *string            `json:"id,omitempty"`
	Name   *string            `json:"name,omitempty"`
	Meters []UtilizationMeter `json:"meters,omitempty"`
}

// NewUtilizationDataCenter instantiates a new UtilizationDataCenter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilizationDataCenter() *UtilizationDataCenter {
	this := UtilizationDataCenter{}

	return &this
}

// NewUtilizationDataCenterWithDefaults instantiates a new UtilizationDataCenter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilizationDataCenterWithDefaults() *UtilizationDataCenter {
	this := UtilizationDataCenter{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UtilizationDataCenter) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDataCenter) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UtilizationDataCenter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UtilizationDataCenter) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UtilizationDataCenter) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDataCenter) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UtilizationDataCenter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UtilizationDataCenter) SetName(v string) {
	o.Name = &v
}

// GetMeters returns the Meters field value if set, zero value otherwise.
func (o *UtilizationDataCenter) GetMeters() []UtilizationMeter {
	if o == nil || IsNil(o.Meters) {
		var ret []UtilizationMeter
		return ret
	}
	return o.Meters
}

// GetMetersOk returns a tuple with the Meters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizationDataCenter) GetMetersOk() ([]UtilizationMeter, bool) {
	if o == nil || IsNil(o.Meters) {
		return nil, false
	}
	return o.Meters, true
}

// HasMeters returns a boolean if a field has been set.
func (o *UtilizationDataCenter) HasMeters() bool {
	if o != nil && !IsNil(o.Meters) {
		return true
	}

	return false
}

// SetMeters gets a reference to the given []UtilizationMeter and assigns it to the Meters field.
func (o *UtilizationDataCenter) SetMeters(v []UtilizationMeter) {
	o.Meters = v
}

func (o UtilizationDataCenter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UtilizationDataCenter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Meters) {
		toSerialize["meters"] = o.Meters
	}
	return toSerialize, nil
}

type NullableUtilizationDataCenter struct {
	value *UtilizationDataCenter
	isSet bool
}

func (v NullableUtilizationDataCenter) Get() *UtilizationDataCenter {
	return v.value
}

func (v *NullableUtilizationDataCenter) Set(val *UtilizationDataCenter) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilizationDataCenter) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilizationDataCenter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilizationDataCenter(val *UtilizationDataCenter) *NullableUtilizationDataCenter {
	return &NullableUtilizationDataCenter{value: val, isSet: true}
}

func (v NullableUtilizationDataCenter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilizationDataCenter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
