/*
 * IONOS Cloud Billing API
 *
 * # Overview The IONOS Billing API is a REST API that can be used to retrieve information about resource usage and invoices. Information on usage is provided without liability.  # Access Permissions Both Contract Owners and Contract Admins have access to the data, but Contract Admins for Reseller Sub-Contracts do not have permission to access the `/invoices` endpoint.
 *
 * API version: 3.9.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package billing

import (
	"encoding/json"
)

// checks if the Traffic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Traffic{}

// Traffic Unified traffic schema. The API returns either VDC-level or NIC-level traffic data depending on the endpoint/query. Both shapes share the same envelope; trafficObj will contain either a 'vdc' array, a 'nic' array, or both.
type Traffic struct {
	Metadata   *TrafficMetadata   `json:"metadata,omitempty"`
	TrafficObj *TrafficTrafficObj `json:"trafficObj,omitempty"`
	TrafficArr [][]interface{}    `json:"trafficArr,omitempty"`
	Traffic    []string           `json:"traffic,omitempty"`
}

// NewTraffic instantiates a new Traffic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraffic() *Traffic {
	this := Traffic{}

	return &this
}

// NewTrafficWithDefaults instantiates a new Traffic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficWithDefaults() *Traffic {
	this := Traffic{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Traffic) GetMetadata() TrafficMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret TrafficMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traffic) GetMetadataOk() (*TrafficMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Traffic) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given TrafficMetadata and assigns it to the Metadata field.
func (o *Traffic) SetMetadata(v TrafficMetadata) {
	o.Metadata = &v
}

// GetTrafficObj returns the TrafficObj field value if set, zero value otherwise.
func (o *Traffic) GetTrafficObj() TrafficTrafficObj {
	if o == nil || IsNil(o.TrafficObj) {
		var ret TrafficTrafficObj
		return ret
	}
	return *o.TrafficObj
}

// GetTrafficObjOk returns a tuple with the TrafficObj field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traffic) GetTrafficObjOk() (*TrafficTrafficObj, bool) {
	if o == nil || IsNil(o.TrafficObj) {
		return nil, false
	}
	return o.TrafficObj, true
}

// HasTrafficObj returns a boolean if a field has been set.
func (o *Traffic) HasTrafficObj() bool {
	if o != nil && !IsNil(o.TrafficObj) {
		return true
	}

	return false
}

// SetTrafficObj gets a reference to the given TrafficTrafficObj and assigns it to the TrafficObj field.
func (o *Traffic) SetTrafficObj(v TrafficTrafficObj) {
	o.TrafficObj = &v
}

// GetTrafficArr returns the TrafficArr field value if set, zero value otherwise.
func (o *Traffic) GetTrafficArr() [][]interface{} {
	if o == nil || IsNil(o.TrafficArr) {
		var ret [][]interface{}
		return ret
	}
	return o.TrafficArr
}

// GetTrafficArrOk returns a tuple with the TrafficArr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traffic) GetTrafficArrOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.TrafficArr) {
		return nil, false
	}
	return o.TrafficArr, true
}

// HasTrafficArr returns a boolean if a field has been set.
func (o *Traffic) HasTrafficArr() bool {
	if o != nil && !IsNil(o.TrafficArr) {
		return true
	}

	return false
}

// SetTrafficArr gets a reference to the given [][]interface{} and assigns it to the TrafficArr field.
func (o *Traffic) SetTrafficArr(v [][]interface{}) {
	o.TrafficArr = v
}

// GetTraffic returns the Traffic field value if set, zero value otherwise.
func (o *Traffic) GetTraffic() []string {
	if o == nil || IsNil(o.Traffic) {
		var ret []string
		return ret
	}
	return o.Traffic
}

// GetTrafficOk returns a tuple with the Traffic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traffic) GetTrafficOk() ([]string, bool) {
	if o == nil || IsNil(o.Traffic) {
		return nil, false
	}
	return o.Traffic, true
}

// HasTraffic returns a boolean if a field has been set.
func (o *Traffic) HasTraffic() bool {
	if o != nil && !IsNil(o.Traffic) {
		return true
	}

	return false
}

// SetTraffic gets a reference to the given []string and assigns it to the Traffic field.
func (o *Traffic) SetTraffic(v []string) {
	o.Traffic = v
}

func (o Traffic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Traffic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.TrafficObj) {
		toSerialize["trafficObj"] = o.TrafficObj
	}
	if !IsNil(o.TrafficArr) {
		toSerialize["trafficArr"] = o.TrafficArr
	}
	if !IsNil(o.Traffic) {
		toSerialize["traffic"] = o.Traffic
	}
	return toSerialize, nil
}

type NullableTraffic struct {
	value *Traffic
	isSet bool
}

func (v NullableTraffic) Get() *Traffic {
	return v.value
}

func (v *NullableTraffic) Set(val *Traffic) {
	v.value = val
	v.isSet = true
}

func (v NullableTraffic) IsSet() bool {
	return v.isSet
}

func (v *NullableTraffic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraffic(val *Traffic) *NullableTraffic {
	return &NullableTraffic{value: val, isSet: true}
}

func (v NullableTraffic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraffic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
